-- Chạy 1 lần trên Supabase SQL Editor
-- Storage → tạo bucket nếu lệnh insert bucket lỗi: vào Storage bấm New bucket
-- tên: practice-uploads, Public: TẮT
-- rồi: NOTIFY pgrst, 'reload schema';

insert into storage.buckets (id, name, public)
values ('practice-uploads', 'practice-uploads', false)
on conflict (id) do nothing;

create table if not exists public.user_file_submissions (
  id bigint generated by default as identity primary key,
  author_name text not null,
  email text,
  zalo text,
  note text,
  file_name text not null,
  storage_path text not null,
  created_at timestamptz not null default now()
);

alter table public.user_file_submissions enable row level security;
revoke all on table public.user_file_submissions from anon, authenticated;

create or replace function public.submit_user_file(
  p_name text,
  p_email text,
  p_zalo text,
  p_note text,
  p_file_name text,
  p_storage_path text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare new_id bigint;
  v_email text := nullif(trim(coalesce(p_email,'')), '');
  v_zalo text := nullif(trim(coalesce(p_zalo,'')), '');
begin
  if length(trim(coalesce(p_name,''))) < 2 then
    raise exception 'name required';
  end if;
  if v_email is null and v_zalo is null then
    raise exception 'email or zalo required';
  end if;
  insert into public.user_file_submissions(author_name, email, zalo, note, file_name, storage_path)
  values (
    left(trim(p_name), 80),
    left(coalesce(v_email,''), 120),
    left(coalesce(v_zalo,''), 40),
    left(coalesce(p_note,''), 400),
    left(coalesce(p_file_name,''), 180),
    left(coalesce(p_storage_path,''), 240)
  )
  returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.admin_list_user_files()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin_user() then raise exception 'not authorized'; end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id', id,
      'name', author_name,
      'email', email,
      'zalo', zalo,
      'note', note,
      'file', file_name,
      'path', storage_path,
      'at', created_at
    ) order by created_at desc)
    from (
      select * from public.user_file_submissions
      order by created_at desc
      limit 100
    ) s
  ), '[]'::jsonb);
end;
$$;

create or replace function public.admin_delete_user_file(p_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin_user() then raise exception 'not authorized'; end if;
  delete from public.user_file_submissions where id = p_id;
end;
$$;

revoke all on function public.submit_user_file(text,text,text,text,text,text) from public;
revoke all on function public.admin_list_user_files() from public;
revoke all on function public.admin_delete_user_file(bigint) from public;
grant execute on function public.submit_user_file(text,text,text,text,text,text) to anon, authenticated;
grant execute on function public.admin_list_user_files() to authenticated;
grant execute on function public.admin_delete_user_file(bigint) to authenticated;

drop policy if exists "practice_uploads_insert" on storage.objects;
create policy "practice_uploads_insert"
on storage.objects for insert to anon, authenticated
with check (bucket_id = 'practice-uploads');

drop policy if exists "practice_uploads_select_auth" on storage.objects;
create policy "practice_uploads_select_auth"
on storage.objects for select to authenticated
using (bucket_id = 'practice-uploads');
