-- Chạy 1 lần trên SQL Editor, rồi: NOTIFY pgrst, 'reload schema';

create table if not exists public.admin_saved_feedback (
  id bigint generated by default as identity primary key,
  kind text not null default 'idea',
  author_name text not null default '',
  message text not null,
  occurred_at timestamptz,
  saved_at timestamptz not null default now()
);

alter table public.admin_saved_feedback enable row level security;
revoke all on table public.admin_saved_feedback from anon, authenticated;

create or replace function public.admin_save_feedback(
  p_kind text,
  p_name text,
  p_message text,
  p_at timestamptz default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare new_id bigint;
begin
  if not public.is_admin_user() then raise exception 'not authorized'; end if;
  insert into public.admin_saved_feedback(kind, author_name, message, occurred_at)
  values (
    left(coalesce(p_kind,'idea'), 20),
    left(coalesce(p_name,''), 80),
    left(coalesce(p_message,''), 1000),
    p_at
  )
  returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.admin_list_saved_feedback()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin_user() then raise exception 'not authorized'; end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id', id,
      'kind', kind,
      'name', author_name,
      'message', message,
      'at', coalesce(occurred_at, saved_at)
    ) order by saved_at desc)
    from public.admin_saved_feedback
  ), '[]'::jsonb);
end;
$$;

create or replace function public.admin_delete_saved_feedback(p_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin_user() then raise exception 'not authorized'; end if;
  delete from public.admin_saved_feedback where id = p_id;
end;
$$;

revoke all on function public.admin_save_feedback(text,text,text,timestamptz) from public;
revoke all on function public.admin_list_saved_feedback() from public;
revoke all on function public.admin_delete_saved_feedback(bigint) from public;
grant execute on function public.admin_save_feedback(text,text,text,timestamptz) to authenticated;
grant execute on function public.admin_list_saved_feedback() to authenticated;
grant execute on function public.admin_delete_saved_feedback(bigint) to authenticated;
