(()=>{'use strict';const $=id=>document.getElementById(id),BUCKET='site-downloads';let tools=[],ideas=[],edit=null,loaded=false,busy=false,mergeSource=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function client(){for(let i=0;i<40;i++){const sb=window.avpSupabase||window.supabaseClient;if(sb?.rpc)return sb;await new Promise(r=>setTimeout(r,100))}throw new Error('connection_unavailable')}
async function rpc(name,args={}){const sb=await client(),res=await sb.rpc(name,args);if(res.error)throw res.error;return res.data}
function uuid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`}
function safeName(v){return String(v||'tool.zip').normalize('NFKD').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').slice(-110)}
function size(n){n=Number(n)||0;if(!n)return '0 B';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<3){n/=1024;i++}return `${n>=10?Math.round(n):n.toFixed(1)} ${u[i]}`}
function note(t){$('atNotice').textContent=t||''}
function reset(){edit=null;$('atToolForm').reset();$('atToolId').value='';$('atToolOrder').value=(tools.reduce((m,x)=>Math.max(m,Number(x.sort_order)||0),0)+1);$('atToolActive').checked=true;$('atFileCurrent').textContent='Chưa có file ZIP đang gắn.';note('');$('atToolName').focus()}
function render(){ $('atTotal').textContent=tools.length;$('atActive').textContent=tools.filter(x=>x.is_active).length;$('atIdeas').textContent=ideas.reduce((a,x)=>a+Number(x.supporters||0),0);
 $('atToolList').innerHTML=tools.length?tools.map(t=>`<article class="at-row"><span class="num">${String(t.sort_order).padStart(2,'0')}</span><div><h4>${esc(t.name)}</h4><p>${esc(t.application||'')}</p><small>${esc(t.file_name)} · ${size(t.file_size)} · ${Number(t.download_count)||0} lượt tải · ${t.is_active?'Đang hiện':'Đang ẩn'}</small></div><div class="at-row-actions"><button type="button" data-at-edit="${t.id}">Sửa</button><button type="button" class="danger" data-at-delete="${t.id}">Xóa</button></div></article>`).join(''):'<div class="at-empty">Chưa có Tool. Dùng form bên trái để thêm Tool đầu tiên.</div>';
 $('atIdeaList').innerHTML=ideas.length?ideas.map((x,i)=>{const merging=mergeSource===x.id;let actions='';if(mergeSource){actions=merging?'<button type="button" data-at-merge-cancel>Hủy gộp</button>':`<button type="button" class="primary" data-at-merge-target="${x.id}">Gộp vào đây</button>`}else{actions=`<button type="button" data-at-idea-rename="${x.id}">Đổi tên</button><button type="button" data-at-merge-source="${x.id}">Gộp</button>`}return `<div class="at-idea-row ${merging?'is-merge-source':''}"><div class="at-idea-title"><strong>${i+1}. ${esc(x.title)}</strong><small>${merging?'Ý tưởng nguồn — chọn ý tưởng đích để cộng dồn lượt.':'Ưu tiên dựa trên số người cùng cần.'}</small></div><b>${Number(x.supporters)||0} lượt</b><select data-at-idea-status="${x.id}"><option value="open" ${x.status==='open'?'selected':''}>Mới</option><option value="planned" ${x.status==='planned'?'selected':''}>Ưu tiên / lên kế hoạch</option><option value="building" ${x.status==='building'?'selected':''}>Đang làm</option><option value="released" ${x.status==='released'?'selected':''}>Đã phát hành</option><option value="hidden" ${x.status==='hidden'?'selected':''}>Ẩn</option></select><div class="at-idea-actions">${actions}</div></div>`}).join(''):'<div class="at-empty">Chưa có ý tưởng Tool từ người dùng.</div>'}
async function load(force=false){if(loaded&&!force){render();return}try{note('Đang tải dữ liệu Tool…');[tools,ideas]=await Promise.all([rpc('admin_tools_catalog_v1'),rpc('admin_tool_ideas_v1')]);tools=tools||[];ideas=ideas||[];loaded=true;render();note('')}catch(e){console.error(e);note('Không tải được Tool. Kiểm tra quyền Admin hoặc SQL TOOL-LIBRARY-V1.sql.')}}
function openEdit(id){edit=tools.find(x=>x.id===id);if(!edit)return;$('atToolId').value=edit.id;$('atToolOrder').value=edit.sort_order;$('atToolName').value=edit.name;$('atToolApplication').value=edit.application||'';$('atToolDescription').value=edit.description||'';$('atToolActive').checked=!!edit.is_active;$('atFileCurrent').innerHTML=`File hiện tại: <b>${esc(edit.file_name)}</b> · ${size(edit.file_size)}`;$('atToolFile').value='';note('Đang sửa Tool. Chỉ chọn ZIP mới nếu muốn thay file.');$('atToolForm').scrollIntoView({behavior:'smooth',block:'start'})}
async function upload(file,id){if(!file||!file.name.toLowerCase().endsWith('.zip'))throw new Error('Chỉ nhận file ZIP.');if(file.size>50*1024*1024)throw new Error('File ZIP không được vượt quá 50 MB.');const sb=await client();const path=`tools/${id}/${Date.now()}-${safeName(file.name)}`;const res=await sb.storage.from(BUCKET).upload(path,file,{upsert:false,contentType:file.type||'application/zip',cacheControl:'3600'});if(res.error)throw res.error;const pub=sb.storage.from(BUCKET).getPublicUrl(path);return {storage_path:path,file_name:file.name,file_size:file.size,file_url:pub?.data?.publicUrl||''}}
async function save(e){e.preventDefault();if(busy)return;busy=true;const btn=$('atToolSave');btn.disabled=true;let uploaded=null;try{const id=edit?.id||uuid(),file=$('atToolFile').files?.[0];let meta=edit?{storage_path:edit.storage_path,file_name:edit.file_name,file_size:edit.file_size,file_url:edit.file_url}:null;if(file){uploaded=await upload(file,id);meta=uploaded}if(!meta)throw new Error('Hãy chọn file ZIP.');const payload={id,sort_order:Number($('atToolOrder').value)||0,name:$('atToolName').value.trim(),application:$('atToolApplication').value.trim(),description:$('atToolDescription').value.trim(),is_active:$('atToolActive').checked,source_path:meta.storage_path,...meta};if(!payload.name)throw new Error('Hãy nhập tên Tool.');await rpc('admin_tool_save_v1',{p_tool:payload});if(uploaded&&edit?.storage_path&&edit.storage_path!==uploaded.storage_path){try{(await client()).storage.from(BUCKET).remove([edit.storage_path])}catch(_){}}await load(true);reset();note('Đã lưu Tool. Trang Kho Tool sẽ nhận dữ liệu mới ngay khi tải lại.')}catch(err){console.error(err);if(uploaded){try{(await client()).storage.from(BUCKET).remove([uploaded.storage_path])}catch(_){}}note(err.message||'Chưa lưu được Tool.')}finally{busy=false;btn.disabled=false}}
async function del(id){const row=tools.find(x=>x.id===id);if(!row||!confirm(`Xóa Tool “${row.name}”?`))return;try{const path=await rpc('admin_tool_delete_v1',{p_id:id});if(path){const sb=await client();await sb.storage.from(BUCKET).remove([path])}await load(true);note('Đã xóa Tool.')}catch(e){note('Chưa xóa được Tool.')}}
async function status(id,value){try{await rpc('admin_tool_idea_status_v1',{p_id:id,p_status:value});await load(true)}catch(e){note('Chưa cập nhật được trạng thái ý tưởng.')}}
async function renameIdea(id){const row=ideas.find(x=>x.id===id);if(!row)return;const title=prompt('Đổi tên ý tưởng Tool:',row.title);if(title===null)return;const clean=title.trim();if(clean.length<5||clean.length>140){note('Tên ý tưởng cần từ 5–140 ký tự.');return}try{await rpc('admin_tool_idea_rename_v1',{p_id:id,p_title:clean});await load(true);note('Đã đổi tên ý tưởng.')}catch(e){note(String(e?.message||'').includes('duplicate_idea')?'Đã có một ý tưởng khác cùng tên. Hãy dùng Gộp để cộng dồn lượt.':'Chưa đổi tên được ý tưởng.')}}
function startMerge(id){mergeSource=id;render();note('Chế độ gộp: chọn “Gộp vào đây” ở ý tưởng bạn muốn giữ lại. Lượt trùng của cùng một người chỉ được tính một lần.')}
function cancelMerge(){mergeSource=null;render();note('')}
async function mergeInto(targetId){const source=ideas.find(x=>x.id===mergeSource),target=ideas.find(x=>x.id===targetId);if(!source||!target||source.id===target.id)return;if(!confirm(`Gộp “${source.title}” vào “${target.title}”? Ý tưởng nguồn sẽ bị xóa và lượt nhu cầu được cộng dồn.`))return;try{const total=await rpc('admin_tool_idea_merge_v1',{p_source_id:source.id,p_target_id:target.id});mergeSource=null;await load(true);note(`Đã gộp ý tưởng. Chủ đề đích hiện có ${Number(total)||0} lượt nhu cầu.`)}catch(e){note('Chưa gộp được ý tưởng.')}}
window.addEventListener('avp:admin-tools-open',()=>load());document.addEventListener('click',e=>{const ed=e.target.closest('[data-at-edit]');if(ed)return openEdit(ed.dataset.atEdit);const de=e.target.closest('[data-at-delete]');if(de)return del(de.dataset.atDelete);const rn=e.target.closest('[data-at-idea-rename]');if(rn)return renameIdea(rn.dataset.atIdeaRename);const ms=e.target.closest('[data-at-merge-source]');if(ms)return startMerge(ms.dataset.atMergeSource);const mt=e.target.closest('[data-at-merge-target]');if(mt)return mergeInto(mt.dataset.atMergeTarget);if(e.target.closest('[data-at-merge-cancel]'))return cancelMerge()});document.addEventListener('change',e=>{if(e.target.matches('[data-at-idea-status]'))status(e.target.dataset.atIdeaStatus,e.target.value)});$('atToolForm')?.addEventListener('submit',save);$('atToolReset')?.addEventListener('click',reset);$('atReload')?.addEventListener('click',()=>load(true));reset();
})();
