-- =========================================================
-- Learn Excel with Anh Van Phong - Admin Analytics
-- Run this file ONCE in Supabase SQL Editor.
-- This does NOT store Excel file contents.
-- =========================================================

-- 1) Admin flag on profiles
alter table public.profiles
add column if not exists is_admin boolean not null default false;

-- 2) Analytics events
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid null references auth.users(id) on delete set null,
  visitor_id text null,
  event_name text not null,
  page_path text null,
  tool_name text null,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists analytics_events_occurred_at_idx
on public.analytics_events (occurred_at desc);

create index if not exists analytics_events_event_name_idx
on public.analytics_events (event_name);

create index if not exists analytics_events_user_id_idx
on public.analytics_events (user_id);

create index if not exists analytics_events_visitor_id_idx
on public.analytics_events (visitor_id);

alter table public.analytics_events enable row level security;

-- Direct table access is intentionally blocked from browser roles.
revoke all on table public.analytics_events from anon, authenticated;

-- ---------------------------------------------------------
-- Helper: is current authenticated user an admin?
-- ---------------------------------------------------------
create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.is_admin = true
  );
$$;

revoke all on function public.is_admin_user() from public;
grant execute on function public.is_admin_user() to authenticated;

-- ---------------------------------------------------------
-- Tracking RPC
-- Accepts anonymous and authenticated visitors.
-- It intentionally does NOT accept Excel file contents.
-- ---------------------------------------------------------
create or replace function public.track_analytics_event(
  p_event_name text,
  p_page text default null,
  p_tool_name text default null,
  p_visitor_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event text;
  v_page text;
  v_tool text;
  v_visitor text;
  v_metadata jsonb;
begin
  v_event := left(trim(coalesce(p_event_name, '')), 64);

  if v_event = '' then
    raise exception 'event_name is required';
  end if;

  -- Allow only a conservative event-name character set.
  if v_event !~ '^[a-zA-Z0-9_.:-]+$' then
    raise exception 'invalid event_name';
  end if;

  v_page := nullif(left(trim(coalesce(p_page, '')), 180), '');
  v_tool := nullif(left(trim(coalesce(p_tool_name, '')), 80), '');
  v_visitor := nullif(left(trim(coalesce(p_visitor_id, '')), 80), '');

  -- Keep metadata small and generic. Never send workbook contents.
  v_metadata := coalesce(p_metadata, '{}'::jsonb);

  if pg_column_size(v_metadata) > 4096 then
    v_metadata := '{}'::jsonb;
  end if;

  insert into public.analytics_events (
    user_id,
    visitor_id,
    event_name,
    page_path,
    tool_name,
    metadata
  )
  values (
    (select auth.uid()),
    v_visitor,
    v_event,
    v_page,
    v_tool,
    v_metadata
  );
end;
$$;

revoke all on function public.track_analytics_event(text,text,text,text,jsonb) from public;
grant execute on function public.track_analytics_event(text,text,text,text,jsonb)
to anon, authenticated;

-- ---------------------------------------------------------
-- Admin Summary RPC
-- ---------------------------------------------------------
create or replace function public.admin_analytics_summary(
  p_days integer default 30
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_days integer := greatest(1, least(coalesce(p_days, 30), 365));
  v_start timestamptz := now() - make_interval(days => greatest(1, least(coalesce(p_days,30),365)));
  v_result jsonb;
begin
  if not public.is_admin_user() then
    raise exception 'admin access required';
  end if;

  select jsonb_build_object(
    'registered_users', (select count(*) from auth.users),
    'new_users_period', (
      select count(*)
      from auth.users
      where created_at >= v_start
    ),
    'page_views', (
      select count(*)
      from public.analytics_events
      where event_name = 'page_view'
        and occurred_at >= v_start
    ),
    'unique_visitors', (
      select count(distinct coalesce(user_id::text, visitor_id))
      from public.analytics_events
      where occurred_at >= v_start
        and coalesce(user_id::text, visitor_id) is not null
    ),
    'active_logged_in_users', (
      select count(distinct user_id)
      from public.analytics_events
      where occurred_at >= v_start
        and user_id is not null
    ),
    'login_events', (
      select count(*)
      from public.analytics_events
      where event_name = 'login'
        and occurred_at >= v_start
    ),
    'excel_mobile_visitors', (
      select count(distinct coalesce(user_id::text, visitor_id))
      from public.analytics_events
      where occurred_at >= v_start
        and coalesce(user_id::text, visitor_id) is not null
        and (
          event_name = 'excel_mobile_open'
          or page_path like '%excel-mobile.html%'
        )
    ),
    'excel_tool_runs', (
      select count(*)
      from public.analytics_events
      where event_name = 'excel_tool_used'
        and occurred_at >= v_start
    ),
    'today_page_views', (
      select count(*)
      from public.analytics_events
      where event_name = 'page_view'
        and occurred_at >= date_trunc('day', now())
    ),
    'today_unique_visitors', (
      select count(distinct coalesce(user_id::text, visitor_id))
      from public.analytics_events
      where occurred_at >= date_trunc('day', now())
        and coalesce(user_id::text, visitor_id) is not null
    )
  )
  into v_result;

  return v_result;
end;
$$;

revoke all on function public.admin_analytics_summary(integer) from public;
grant execute on function public.admin_analytics_summary(integer) to authenticated;

-- ---------------------------------------------------------
-- Daily trend RPC
-- ---------------------------------------------------------
create or replace function public.admin_analytics_trend(
  p_days integer default 30
)
returns table (
  day date,
  page_views bigint,
  unique_visitors bigint,
  tool_runs bigint,
  logins bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_days integer := greatest(1, least(coalesce(p_days,30), 90));
begin
  if not public.is_admin_user() then
    raise exception 'admin access required';
  end if;

  return query
  with days as (
    select generate_series(
      current_date - (v_days - 1),
      current_date,
      interval '1 day'
    )::date as d
  )
  select
    days.d,
    count(*) filter (where e.event_name = 'page_view')::bigint as page_views,
    count(distinct coalesce(e.user_id::text, e.visitor_id))
      filter (where coalesce(e.user_id::text, e.visitor_id) is not null)::bigint as unique_visitors,
    count(*) filter (where e.event_name = 'excel_tool_used')::bigint as tool_runs,
    count(*) filter (where e.event_name = 'login')::bigint as logins
  from days
  left join public.analytics_events e
    on e.occurred_at >= days.d
   and e.occurred_at < days.d + interval '1 day'
  group by days.d
  order by days.d;
end;
$$;

revoke all on function public.admin_analytics_trend(integer) from public;
grant execute on function public.admin_analytics_trend(integer) to authenticated;

-- ---------------------------------------------------------
-- Top tools RPC
-- ---------------------------------------------------------
create or replace function public.admin_analytics_top_tools(
  p_days integer default 30,
  p_limit integer default 10
)
returns table (
  tool_name text,
  uses bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_days integer := greatest(1, least(coalesce(p_days,30),365));
  v_limit integer := greatest(1, least(coalesce(p_limit,10),50));
begin
  if not public.is_admin_user() then
    raise exception 'admin access required';
  end if;

  return query
  select
    coalesce(e.tool_name, '(không xác định)') as tool_name,
    count(*)::bigint as uses
  from public.analytics_events e
  where e.event_name = 'excel_tool_used'
    and e.occurred_at >= now() - make_interval(days => v_days)
  group by coalesce(e.tool_name, '(không xác định)')
  order by count(*) desc, tool_name
  limit v_limit;
end;
$$;

revoke all on function public.admin_analytics_top_tools(integer,integer) from public;
grant execute on function public.admin_analytics_top_tools(integer,integer) to authenticated;

-- ---------------------------------------------------------
-- Top pages RPC
-- ---------------------------------------------------------
create or replace function public.admin_analytics_top_pages(
  p_days integer default 30,
  p_limit integer default 10
)
returns table (
  page_path text,
  views bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_days integer := greatest(1, least(coalesce(p_days,30),365));
  v_limit integer := greatest(1, least(coalesce(p_limit,10),50));
begin
  if not public.is_admin_user() then
    raise exception 'admin access required';
  end if;

  return query
  select
    coalesce(e.page_path, '(không xác định)') as page_path,
    count(*)::bigint as views
  from public.analytics_events e
  where e.event_name = 'page_view'
    and e.occurred_at >= now() - make_interval(days => v_days)
  group by coalesce(e.page_path, '(không xác định)')
  order by count(*) desc, page_path
  limit v_limit;
end;
$$;

revoke all on function public.admin_analytics_top_pages(integer,integer) from public;
grant execute on function public.admin_analytics_top_pages(integer,integer) to authenticated;

-- =========================================================
-- IMPORTANT: Make YOUR account an admin.
-- Replace YOUR_EMAIL@example.com with the email you use to log in.
-- Run this ONE command after the SQL above:
--
-- update public.profiles
-- set is_admin = true
-- where id = (
--   select id from auth.users
--   where email = 'YOUR_EMAIL@example.com'
-- );
--
-- Verify:
-- select id, display_name, is_admin from public.profiles where is_admin = true;
-- =========================================================
