-- AVP Content OS V1
-- Run this in Supabase SQL Editor after the frontend files are deployed.
create table if not exists public.content_items_v1 (id uuid primary key default gen_random_uuid(), content_code text not null unique, title text not null check(char_length(btrim(title)) between 2 and 180), status text not null default 'idea' check(status in('idea','selected','draft','audit','need_fix','pass')), priority text not null default 'normal' check(priority in('low','normal','high')), channel text not null default 'tiktok', industry text, excel_skills text[] not null default '{}', case_title text, case_description text, hook text, script text, excel_logic text, practice_file_path text, practice_file_name text, tiktok_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), passed_at timestamptz, published_at timestamptz);
create table if not exists public.content_audits_v1 (id uuid primary key default gen_random_uuid(), content_id uuid not null references public.content_items_v1(id) on delete cascade, result text not null check(result in('pass','fail')), audit_type text not null default 'full', issues text[] not null default '{}', suggestions text[] not null default '{}', created_at timestamptz not null default now());
alter table public.content_items_v1 enable row level security; alter table public.content_audits_v1 enable row level security;
drop policy if exists content_items_admin_select on public.content_items_v1; create policy content_items_admin_select on public.content_items_v1 for select to authenticated using(coalesce((select is_admin from public.profiles where id=(select auth.uid())),false));
drop policy if exists content_items_admin_insert on public.content_items_v1; create policy content_items_admin_insert on public.content_items_v1 for insert to authenticated with check(coalesce((select is_admin from public.profiles where id=(select auth.uid())),false));
drop policy if exists content_items_admin_update on public.content_items_v1; create policy content_items_admin_update on public.content_items_v1 for update to authenticated using(coalesce((select is_admin from public.profiles where id=(select auth.uid())),false)) with check(coalesce((select is_admin from public.profiles where id=(select auth.uid())),false));
drop policy if exists content_items_admin_delete on public.content_items_v1; create policy content_items_admin_delete on public.content_items_v1 for delete to authenticated using(coalesce((select is_admin from public.profiles where id=(select auth.uid())),false));
drop policy if exists content_audits_admin_select on public.content_audits_v1; create policy content_audits_admin_select on public.content_audits_v1 for select to authenticated using(coalesce((select is_admin from public.profiles where id=(select auth.uid())),false));
drop policy if exists content_audits_admin_insert on public.content_audits_v1; create policy content_audits_admin_insert on public.content_audits_v1 for insert to authenticated with check(coalesce((select is_admin from public.profiles where id=(select auth.uid())),false));
create or replace function public.avp_content_dashboard_v1() returns jsonb language sql stable security invoker as $$ select jsonb_build_object('idea',count(*) filter(where status='idea'),'selected',count(*) filter(where status='selected'),'draft',count(*) filter(where status='draft'),'audit',count(*) filter(where status='audit'),'need_fix',count(*) filter(where status='need_fix'),'pass',count(*) filter(where status='pass'),'total',count(*)) from public.content_items_v1 $$;
create or replace function public.avp_content_list_v1(p_search text default null,p_status text default null) returns setof public.content_items_v1 language sql stable security invoker as $$ select * from public.content_items_v1 where (p_status is null or p_status='' or status=p_status) and (p_search is null or btrim(p_search)='' or title ilike '%'||btrim(p_search)||'%' or coalesce(case_title,'') ilike '%'||btrim(p_search)||'%' or coalesce(industry,'') ilike '%'||btrim(p_search)||'%') order by updated_at desc $$;
create or replace function public.avp_content_save_v1(p_content jsonb) returns public.content_items_v1 language plpgsql security definer set search_path=public as $$ declare r public.content_items_v1; begin if coalesce((select is_admin from public.profiles where id=(select auth.uid())),false) is not true then raise exception 'ADMIN_REQUIRED'; end if; insert into public.content_items_v1(id,content_code,title,status,priority,channel,industry,excel_skills,case_title,case_description,hook,script,excel_logic,practice_file_name,tiktok_url) values(coalesce(nullif(p_content->>'id','')::uuid,gen_random_uuid()),coalesce(nullif(p_content->>'content_code',''),'AVP-'||to_char(now(),'YYYYMMDD-HH24MISS')),btrim(p_content->>'title'),coalesce(nullif(p_content->>'status',''),'idea'),coalesce(nullif(p_content->>'priority',''),'normal'),coalesce(nullif(p_content->>'channel',''),'tiktok'),nullif(btrim(p_content->>'industry'),''),coalesce(array(select jsonb_array_elements_text(coalesce(p_content->'excel_skills','[]'::jsonb))),'{}'),nullif(btrim(p_content->>'case_title'),''),nullif(p_content->>'case_description',''),nullif(p_content->>'hook',''),nullif(p_content->>'script',''),nullif(p_content->>'excel_logic',''),nullif(p_content->>'practice_file_name',''),nullif(p_content->>'tiktok_url','')) on conflict(id) do update set content_code=excluded.content_code,title=excluded.title,status=excluded.status,priority=excluded.priority,channel=excluded.channel,industry=excluded.industry,excel_skills=excluded.excel_skills,case_title=excluded.case_title,case_description=excluded.case_description,hook=excluded.hook,script=excluded.script,excel_logic=excluded.excel_logic,practice_file_name=excluded.practice_file_name,tiktok_url=excluded.tiktok_url,updated_at=now() returning * into r; return r; end $$;
create or replace function public.avp_content_delete_v1(p_id uuid) returns boolean language plpgsql security definer set search_path=public as $$ begin if coalesce((select is_admin from public.profiles where id=(select auth.uid())),false) is not true then raise exception 'ADMIN_REQUIRED'; end if; delete from public.content_items_v1 where id=p_id; return found; end $$;
create or replace function public.avp_content_audit_v1(p_content_id uuid,p_result text,p_issues text[] default '{}',p_suggestions text[] default '{}') returns public.content_audits_v1 language plpgsql security definer set search_path=public as $$ declare r public.content_audits_v1; begin if coalesce((select is_admin from public.profiles where id=(select auth.uid())),false) is not true then raise exception 'ADMIN_REQUIRED'; end if; insert into public.content_audits_v1(content_id,result,issues,suggestions) values(p_content_id,lower(p_result),coalesce(p_issues,'{}'),coalesce(p_suggestions,'{}')) returning * into r; update public.content_items_v1 set status=case when lower(p_result)='pass' then 'pass' else 'need_fix' end,passed_at=case when lower(p_result)='pass' then now() else passed_at end,updated_at=now() where id=p_content_id; return r; end $$;
revoke all on function public.avp_content_dashboard_v1() from public,anon; revoke all on function public.avp_content_list_v1(text,text) from public,anon; revoke all on function public.avp_content_save_v1(jsonb) from public,anon; revoke all on function public.avp_content_delete_v1(uuid) from public,anon; revoke all on function public.avp_content_audit_v1(uuid,text,text[],text[]) from public,anon;
grant execute on function public.avp_content_dashboard_v1() to authenticated; grant execute on function public.avp_content_list_v1(text,text) to authenticated; grant execute on function public.avp_content_save_v1(jsonb) to authenticated; grant execute on function public.avp_content_delete_v1(uuid) to authenticated; grant execute on function public.avp_content_audit_v1(uuid,text,text[],text[]) to authenticated;