(function(){
 const XPKEY='avp_xp_v2', QUIZKEY='avp_quiz_done_v1';
 const lessons={
 'excel.html':{level:'Cơ bản',mins:15,xp:20,obj:['Hiểu cấu trúc Workbook, Worksheet và ô dữ liệu','Nhập và định dạng dữ liệu đúng cách','Biết các thao tác nền tảng cần dùng hằng ngày'],practice:'Tạo một bảng theo dõi công việc 10 dòng, định dạng tiêu đề và ngày tháng.',q:'Workbook trong Excel là gì?',opts:['Một ô dữ liệu','Một file Excel có thể chứa nhiều sheet','Một công thức','Một biểu đồ'],ans:1},
 'phimtatexcel.html':{level:'Cơ bản',mins:15,xp:20,obj:['Ghi nhớ nhóm phím tắt thiết yếu','Tăng tốc nhập liệu và chỉnh sửa','Biết chọn phím tắt theo tình huống'],practice:'Chọn 10 phím tắt bạn dùng nhiều nhất và thực hiện liên tục không dùng chuột.',q:'Phím tắt Ctrl + S dùng để làm gì?',opts:['Tìm kiếm','Lưu file','In','Đóng file'],ans:1},
 'congthucexcel.html':{level:'Cơ bản',mins:20,xp:25,obj:['Hiểu cú pháp công thức','Phân biệt tham chiếu tương đối và tuyệt đối','Biết chọn nhóm hàm phù hợp'],practice:'Tạo bảng 20 dòng và dùng SUM, COUNTIF, IF để tạo 3 chỉ số tổng hợp.',q:'Hàm nào dùng để đếm theo điều kiện?',opts:['SUM','COUNTIF','LEFT','ROUND'],ans:1},
 'filtersort.html':{level:'Cơ bản',mins:12,xp:20,obj:['Lọc dữ liệu theo điều kiện','Sắp xếp một hoặc nhiều cột','Tránh lỗi khi lọc vùng dữ liệu'],practice:'Lọc danh sách chỉ còn các dòng NG rồi sắp xếp theo số lượng giảm dần.',q:'Filter dùng chủ yếu để làm gì?',opts:['Ẩn tạm các dòng không thỏa điều kiện','Xóa dữ liệu','Tạo biểu đồ','Khóa sheet'],ans:0},
 'pivottable.html':{level:'Ứng dụng',mins:25,xp:35,obj:['Hiểu Rows, Columns, Values, Filters','Tạo báo cáo tổng hợp từ dữ liệu thô','Biết Refresh khi nguồn dữ liệu thay đổi'],practice:'Từ bảng Lot / Model / Input / NG, tạo PivotTable tổng hợp NG theo Model và tính tỷ lệ.',q:'Khi dữ liệu nguồn thay đổi, thao tác nào giúp PivotTable cập nhật?',opts:['Merge','Refresh','Freeze Panes','Wrap Text'],ans:1},
 'bieudopareto.html':{level:'Ứng dụng',mins:20,xp:30,obj:['Hiểu nguyên tắc Pareto','Tính % tích lũy','Xác định nhóm lỗi ưu tiên'],practice:'Lập Pareto cho 8 loại lỗi và xác định nhóm gây khoảng 80% tổng NG.',q:'Đường trong biểu đồ Pareto thường thể hiện gì?',opts:['Giá trị trung bình','% tích lũy','Ngày tháng','Số sheet'],ans:1},
 'baocaoexcel.html':{level:'Ứng dụng',mins:25,xp:35,obj:['Thiết kế báo cáo dễ đọc','Chọn KPI phù hợp','Tổ chức dữ liệu trước khi trực quan hóa'],practice:'Tạo báo cáo một trang gồm Input, NG, NG Rate và Top 5 lỗi.',q:'KPI trên dashboard nên ưu tiên điều gì?',opts:['Càng nhiều càng tốt','Chỉ số liên quan trực tiếp mục tiêu','Màu thật nhiều','Font thật nhỏ'],ans:1},
 'excel-nang-cao.html':{level:'Nâng cao',mins:30,xp:40,obj:['Chọn công cụ nâng cao phù hợp','Kết hợp Power Query, XLOOKUP và Dynamic Array','Thiết kế quy trình xử lý dữ liệu ít thao tác tay'],practice:'Phác thảo quy trình từ 10 file nhập liệu đến một Master và báo cáo cuối.',q:'Công cụ phù hợp nhất để gộp nhiều file cùng cấu trúc?',opts:['WordArt','Power Query','Goal Seek','Format Painter'],ans:1},
 'power-pivot-dax.html':{level:'Nâng cao',mins:30,xp:45,obj:['Hiểu Data Model và Relationship','Phân biệt calculated column và measure','Viết measure DAX cơ bản'],practice:'Tạo measure Total NG và NG Rate bằng DIVIDE.',q:'Measure trong Power Pivot thường được viết bằng ngôn ngữ nào?',opts:['HTML','DAX','VBA only','SQL Server Agent'],ans:1},
 'dashboard-dong.html':{level:'Nâng cao',mins:30,xp:45,obj:['Thiết kế dashboard theo KPI','Dùng Slicer/Timeline để tương tác','Tạo bố cục dễ ra quyết định'],practice:'Tạo dashboard có 4 KPI, trend NG và Top Defect, điều khiển bằng Slicer.',q:'Slicer hữu ích nhất cho việc gì?',opts:['Lọc báo cáo tương tác','Đổi mật khẩu','Viết Macro','Nén file'],ans:0},
 'vba-macro.html':{level:'Master',mins:35,xp:50,obj:['Hiểu Macro và VBA','Record Macro an toàn','Tự động hóa thao tác lặp'],practice:'Record một macro định dạng báo cáo, sau đó gắn macro vào một nút.',q:'Macro phù hợp nhất với loại công việc nào?',opts:['Thao tác lặp lại có quy trình rõ','Mọi quyết định phức tạp','Thiết kế logo','Dịch ngôn ngữ'],ans:0},
 'solver-whatif.html':{level:'Master',mins:30,xp:50,obj:['Phân biệt Goal Seek và Solver','Thiết lập biến, mục tiêu và ràng buộc','Giải bài toán tối ưu đơn giản'],practice:'Dùng Goal Seek tìm Input cần thiết để đạt một mục tiêu Output, sau đó thử Solver với ràng buộc.',q:'Goal Seek phù hợp khi bạn muốn?',opts:['Tìm giá trị đầu vào để đạt một kết quả mục tiêu','Gộp file','Tạo PivotTable','Đổi font'],ans:0}
 };
 function file(){return (location.pathname.split('/').pop()||'index.html').toLowerCase()}
 function getXP(){return +(localStorage.getItem(XPKEY)||0)}
 function addXP(v){localStorage.setItem(XPKEY,getXP()+v)}
 function done(){try{return JSON.parse(localStorage.getItem(QUIZKEY)||'{}')}catch(e){return{}}}
 function saveDone(v){localStorage.setItem(QUIZKEY,JSON.stringify(v))}
 function toast(t){const el=document.createElement('div');el.className='xp-toast';el.textContent=t;document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
 function inject(){const f=file(),m=lessons[f];if(!m)return;const target=document.querySelector('main')||document.body; const shell=document.createElement('section');shell.className='course-shell';shell.innerHTML=`<div class="course-panel"><div class="course-top"><div><span class="course-kicker">${m.level} • Bài học có lộ trình</span><h2 class="course-title">Học theo mục tiêu — làm được sau khi học</h2><div class="course-meta">⏱ ${m.mins} phút • 🎯 Thực hành ngay • 🏅 +${m.xp} XP khi vượt quiz</div></div><div class="course-xp">⚡ ${getXP()} XP</div></div><div class="course-grid"><div class="course-box"><h3>🎯 Mục tiêu bài học</h3><ul>${m.obj.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="course-box"><h3>✅ Cách học đề xuất</h3><ul><li>Đọc phần chính</li><li>Làm lại ví dụ bằng Excel</li><li>Hoàn thành bài thực hành</li><li>Làm quiz cuối bài</li></ul></div></div><div class="course-practice"><strong>🧪 Bài thực hành:</strong> ${m.practice}</div><div class="course-complete-box"><h3>✓ Bạn hoàn thành bài này khi</h3><ul><li>Đã đọc và hiểu các mục tiêu bên trên</li><li>Đã làm bài thực hành trên file Excel</li><li>Đã vượt quiz cuối bài (+${m.xp} XP)</li></ul></div></div>`; target.parentNode.insertBefore(shell,target);
 const q=document.createElement('section');q.className='quiz-panel';const already=!!done()[f];q.innerHTML=`<div class="quiz-card"><span class="course-kicker">QUIZ CUỐI BÀI</span><h2>Kiểm tra nhanh</h2><p>Trả lời đúng để ghi nhận hoàn thành và nhận XP.</p><div class="quiz-q">${m.q}</div><div class="quiz-options">${m.opts.map((x,i)=>`<button class="quiz-opt" data-i="${i}">${x}</button>`).join('')}</div><div class="quiz-actions"><button class="quiz-submit">Kiểm tra đáp án</button><span class="quiz-result">${already?'✓ Đã vượt quiz — XP đã được ghi nhận':''}</span></div></div>`;document.body.insertBefore(q,document.querySelector('footer')||null);
 let selected=null; q.querySelectorAll('.quiz-opt').forEach(b=>b.onclick=()=>{selected=+b.dataset.i;q.querySelectorAll('.quiz-opt').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});q.querySelector('.quiz-submit').onclick=()=>{if(selected===null){q.querySelector('.quiz-result').textContent='Chọn một đáp án trước.';return}q.querySelectorAll('.quiz-opt').forEach((b,i)=>{b.classList.remove('correct','wrong');if(i===m.ans)b.classList.add('correct');else if(i===selected)b.classList.add('wrong')});const passed=selected===m.ans;try{window.avpAnalytics?.track('quiz_attempt',{page:f,metadata:{passed,score:passed?1:0,total:1}})}catch(e){}if(passed){const d=done();if(!d[f]){d[f]=true;saveDone(d);addXP(m.xp);toast(`+${m.xp} XP — Hoàn thành quiz!`);try{window.avpAnalytics?.track('lesson_complete',{page:f,metadata:{xp:m.xp}})}catch(e){}window.dispatchEvent(new CustomEvent('avp:course-xp',{detail:{xp:m.xp,file:f}}))}q.querySelector('.quiz-result').textContent='✓ Chính xác! Bài học đã được ghi nhận.'}else q.querySelector('.quiz-result').textContent='Chưa đúng. Xem lại nội dung rồi thử lại nhé.'};
 }
 document.addEventListener('DOMContentLoaded',inject);
})();
