(() => {
  "use strict";
  const BANK=window.AVPArenaBank;
  const LEVEL_TITLES=["Tân binh","Văn phòng","Analyst","Specialist","Pro","Master"];
  const MAX_DIFFICULTY=[1,2,3,4,5,5];
  const $=id=>document.getElementById(id);
  const qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const state={mode:"learn",topic:"mixed",running:false,player:"",current:null,used:new Set(),recentConcepts:[],retryQueue:[],sequence:0,correct:0,score:0,combo:0,perfectStreak:0,bestPerfect:0,lives:3,level:1,raf:0,questionStart:0,duration:12000,locked:false};

  function topicMeta(id){if(id==="mixed")return{id:"mixed",icon:"🔥",name:"Tổng hợp Excel",desc:"Toàn bộ chủ đề · thử thách khó nhất"};return BANK?.topics?.find(t=>t.id===id)||{id,icon:"⚡",name:id,desc:""}}
  function stripMarks(v){return String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
  function normalize(v){return stripMarks(v).replace(/&/g," and ").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," ")}
  function compact(v){return normalize(v).replace(/\s+/g,"")}
  function commandForm(v){return stripMarks(v).replace(/[\s+]+/g,"")}
  function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]))}
  function levenshtein(a,b){a=String(a);b=String(b);if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;const p=Array.from({length:b.length+1},(_,i)=>i),c=new Array(b.length+1);for(let i=1;i<=a.length;i++){c[0]=i;for(let j=1;j<=b.length;j++)c[j]=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<=b.length;j++)p[j]=c[j]}return p[b.length]}
  function evaluateAnswer(raw,q){const n=normalize(raw);if(!n)return{ok:false,grade:"empty"};const special=/[+=;]/.test(q.answer);if(special){if(commandForm(raw)===commandForm(q.answer))return{ok:true,grade:"perfect"}}else if(n===normalize(q.answer))return{ok:true,grade:"perfect"};if((q.aliases||[]).map(normalize).includes(n))return{ok:true,grade:"meaning"};if(!special){const a=compact(raw),b=compact(q.answer);if(b.length>=5){const d=levenshtein(a,b),m=b.length>=9?2:1;if(d<=m)return{ok:true,grade:"near"}}}return{ok:false,grade:"wrong"}}
  function shuffle(arr){const out=arr.slice();for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
  function maxDifficulty(){return MAX_DIFFICULTY[Math.min(state.level-1,MAX_DIFFICULTY.length-1)]||5}
  function sourceQuestions(){return state.topic==="mixed"?BANK.questions:(BANK.byTopic[state.topic]||[])}
  function eligibleQuestions(boss=false){const md=maxDifficulty();return sourceQuestions().filter(q=>q.difficulty<=md&&q.boss===boss&&!state.used.has(q.id))}
  function spacedPool(pool){const spaced=pool.filter(q=>!state.recentConcepts.includes(q.conceptId));return spaced.length?spaced:pool}
  function rememberConcept(q){if(!q?.conceptId)return;state.recentConcepts.push(q.conceptId);const cap=state.topic==="mixed"?12:Math.min(8,Math.max(4,new Set(sourceQuestions().map(x=>x.conceptId)).size-1));while(state.recentConcepts.length>cap)state.recentConcepts.shift()}
  function pickQuestion(){
    if(state.mode==="learn"){const i=state.retryQueue.findIndex(x=>x.dueAt<=state.sequence);if(i>=0){const[item]=state.retryQueue.splice(i,1);rememberConcept(item.q);return{...item.q,isRetry:true}}}
    const wantsBoss=state.sequence>0&&(state.sequence+1)%10===0;let pool=eligibleQuestions(wantsBoss);if(!pool.length)pool=eligibleQuestions(false);
    if(!pool.length){const md=maxDifficulty(),source=sourceQuestions();pool=source.filter(q=>q.difficulty<=md&&q.boss===wantsBoss);if(!pool.length)pool=source.filter(q=>q.difficulty<=md&&!q.boss);if(pool.length){const ids=new Set(pool.map(q=>q.id));for(const id of Array.from(state.used))if(ids.has(id))state.used.delete(id)}}
    pool=spacedPool(pool);const q=shuffle(pool)[0]||shuffle(BANK.questions)[0];if(q){state.used.add(q.id);rememberConcept(q)}return q
  }
  function durationFor(q){const d=q?.difficulty||1;if(state.mode==="learn")return Math.max(10500,21000-d*1700);return Math.max(6000,16800-(state.level-1)*1150-d*650)}
  function levelFromCorrect(){return Math.min(6,1+Math.floor(state.correct/8))}
  function updateHud(){state.level=levelFromCorrect();$("hudLevel").textContent=state.level;$("hudTitle").textContent=LEVEL_TITLES[state.level-1]||"Master";$("hudScore").textContent=state.score.toLocaleString("vi-VN");$("hudCombo").textContent=state.combo;$("hudPerfect").textContent=`Perfect ${state.perfectStreak}`;$("hudQuestion").textContent=state.sequence;const count=state.topic==="mixed"?BANK.totalQuestions:(BANK.topicCounts[state.topic]||0);$("hudPool").textContent=`${state.used.size}/${count} đã gặp`;$("hudLives").textContent=state.mode==="rank"?"❤️".repeat(Math.max(0,state.lives)):"∞";$("hudBest").textContent=`Best P${state.bestPerfect}`}
  function feedback(kind,html){const e=$("arenaFeedback");e.className=`arena-feedback ${kind||""}`.trim();e.innerHTML=html}
  function stopAnimation(){if(state.raf)cancelAnimationFrame(state.raf);state.raf=0}
  function animate(now){if(!state.running||state.locked||!state.current)return;const elapsed=now-state.questionStart,remaining=Math.max(0,1-elapsed/state.duration),percent=remaining*100;$("arenaTarget").style.left=`${percent}%`;$("timerFill").style.width=`${percent}%`;if(remaining<=0){handleMiss("timeout");return}state.raf=requestAnimationFrame(animate)}
  function renderQuestion(q){if(!q)return endGame("Không còn câu phù hợp.");state.current=q;state.locked=false;state.sequence++;state.level=levelFromCorrect();state.duration=durationFor(q);state.questionStart=performance.now();const meta=topicMeta(q.topic);$("targetIcon").textContent=meta.icon;$("targetLabel").textContent=q.boss?"BOSS":q.isRetry?"ÔN LẠI":"TARGET";$("arenaTarget").className=`arena-target${q.boss?" is-boss":""}`;$("arenaTarget").style.left="100%";$("timerFill").style.width="100%";$("questionDifficulty").textContent=`Độ khó ${q.difficulty}/5`;$("bossBadge").hidden=!q.boss;$("questionPrompt").textContent=q.prompt;$("answerGuide").textContent=q.isRetry?"Câu này đã từng sai. Hãy thử nhớ lại trước khi gõ.":"Gõ tên chuẩn để lấy Perfect; tiếng Việt đúng ý vẫn được tính.";$("answerInput").value="";$("answerInput").disabled=false;$("answerInput").focus({preventScroll:true});feedback("",q.isRetry?"↻ Câu sai quay lại đúng lịch ôn.":"Nhấn Enter để tung đòn.");updateHud();stopAnimation();state.raf=requestAnimationFrame(animate)}
  function queueRetry(q){if(state.mode!=="learn"||!q)return;const cid=q.conceptId;if(state.retryQueue.some(x=>x.q.conceptId===cid))return;const source=sourceQuestions().filter(x=>x.conceptId===cid&&!x.boss),retry=shuffle(source)[0]||q,gap=3+Math.floor(Math.random()*5);state.retryQueue.push({q:retry,dueAt:state.sequence+gap})}
  function nextAfter(ms){setTimeout(()=>{if(state.running)renderQuestion(pickQuestion())},ms)}
  function correctPoints(grade,q){const elapsed=performance.now()-state.questionStart,timeRatio=Math.max(0,1-elapsed/state.duration),base=grade==="perfect"?120:grade==="meaning"?85:65,d=Math.max(1,q.difficulty||1),mult=Math.min(2,1+state.combo*.04);return Math.round((base*d+80*timeRatio)*mult)}
  function handleCorrect(result){if(state.locked||!state.current)return;state.locked=true;stopAnimation();$("answerInput").disabled=true;const q=state.current;state.correct++;state.combo++;if(result.grade==="perfect"){state.perfectStreak++;state.bestPerfect=Math.max(state.bestPerfect,state.perfectStreak)}else state.perfectStreak=0;const pts=correctPoints(result.grade,q);state.score+=pts;$("arenaTarget").classList.add("is-hit");const label=result.grade==="perfect"?"PERFECT":result.grade==="meaning"?"ĐÚNG Ý":"GẦN ĐÚNG",note=result.grade==="perfect"?"Tên chuẩn chính xác.":result.grade==="meaning"?"Bạn hiểu đúng. Hãy ghi nhớ tên chuẩn.":"Chấp nhận lỗi chính tả nhẹ; hãy nhớ cách viết chuẩn.";feedback("good",`<strong>${label} +${pts}</strong> · ${escapeHtml(q.answer)} — ${escapeHtml(q.meaning)}<br>${note}`);updateHud();nextAfter(950)}
  function handleMiss(reason){if(state.locked||!state.current)return;state.locked=true;stopAnimation();$("answerInput").disabled=true;const q=state.current;state.combo=0;state.perfectStreak=0;queueRetry(q);if(state.mode==="rank")state.lives--;feedback("bad",`<strong>${reason==="timeout"?"HẾT GIỜ":"CHƯA ĐÚNG"}</strong> · Đáp án chuẩn: ${escapeHtml(q.answer)} — ${escapeHtml(q.meaning)}${state.mode==="learn"?"<br>Câu này sẽ quay lại sau vài lượt.":""}`);updateHud();if(state.mode==="rank"&&state.lives<=0)setTimeout(()=>endGame("Hết 3 mạng."),1200);else nextAfter(1250)}

  async function waitClient(timeout=5500){const start=Date.now();while(Date.now()-start<timeout){const c=window.avpSupabase||window.supabaseClient;if(c)return c;await new Promise(r=>setTimeout(r,80))}return window.avpSupabase||window.supabaseClient||null}
  async function currentSession(){const client=await waitClient();if(!client?.auth)return{client:null,user:null};try{const{data}=await client.auth.getSession();return{client,user:data?.session?.user||null}}catch{return{client,user:null}}}
  async function syncIdentity(){const{client,user}=await currentSession();if(!user){state.player="";$("playerName").textContent="Chưa đăng nhập";$("loginMessage").textContent="Đăng nhập để chơi và ghi thành tích Rank.";return false}let name=user.user_metadata?.display_name||user.user_metadata?.full_name||user.email?.split("@")[0]||"Học viên";try{const{data,error}=await client.rpc("arena_identity_v1");if(!error&&data?.player_name)name=String(data.player_name)}catch{}state.player=name;$("playerName").textContent=name;$("loginMessage").textContent="Season 1 · BXH cũ không được mang sang Arena.";return true}
  async function submitRank(){if(state.mode!=="rank"||!state.player||state.score<=0)return;const client=await waitClient();if(!client?.rpc)return;try{const{error}=await client.rpc("arena_submit_score_v1",{p_topic:state.topic,p_score:state.score,p_level:state.level,p_perfect_streak:state.bestPerfect,p_correct_count:state.correct});if(error)throw error}catch(err){console.warn("[arena] submit rank",err);feedback("warn","Thành tích trên máy đã giữ, nhưng chưa đồng bộ được BXH.")}}
  function localBestKey(){return`avp_arena_s1_best_${state.topic}`}
  function saveLocalBest(){try{const old=Number(localStorage.getItem(localBestKey())||0);if(state.score>old)localStorage.setItem(localBestKey(),String(state.score))}catch{}}
  async function endGame(reason="Đã dừng lượt chơi."){if(!state.running)return;state.running=false;state.locked=true;stopAnimation();$("answerInput").disabled=true;saveLocalBest();if(state.mode==="rank")await submitRank();feedback("warn",`<strong>${escapeHtml(reason)}</strong> ${state.mode==="rank"?"Rank":"Học"} kết thúc với ${state.score.toLocaleString("vi-VN")} điểm · ${state.correct} câu đúng · Perfect tốt nhất ${state.bestPerfect}.`);$("stopArena").textContent="Đã dừng";$("stopArena").disabled=true;loadBoard(state.topic)}
  function resetRun(){stopAnimation();Object.assign(state,{running:true,current:null,retryQueue:[],sequence:0,correct:0,score:0,combo:0,perfectStreak:0,bestPerfect:0,lives:3,level:1,locked:false});state.used=new Set();state.recentConcepts=[];$("stopArena").textContent="Dừng";$("stopArena").disabled=false}
  async function startGame(){if(!BANK?.questions?.length){$("setupHint").textContent="Không tải được ngân hàng câu hỏi.";return}if(!await syncIdentity()){$("setupHint").textContent="Bạn cần đăng nhập trước khi vào Arena.";return}resetRun();$("arenaSetup").hidden=true;$("arenaGame").hidden=false;$("currentMode").textContent=state.mode==="rank"?"Rank · 3 mạng":"Học · ôn lặp thông minh";$("currentTopic").textContent=topicMeta(state.topic).name;$("boardTopic").value=state.topic;updateHud();renderQuestion(pickQuestion());$("arenaGame").scrollIntoView({behavior:"smooth",block:"start"})}
  function showSetup(){if(state.running)endGame("Bạn đã rời lượt chơi.");$("arenaGame").hidden=true;$("arenaSetup").hidden=false;$("arenaSetup").scrollIntoView({behavior:"smooth",block:"start"})}

  function renderTopics(){const root=$("topicGrid"),cards=[{id:"mixed",icon:"🔥",name:"Tổng hợp Excel",desc:"Tất cả chủ đề · phù hợp Rank tổng hợp",count:BANK.totalQuestions},...BANK.topics.map(t=>({...t,count:BANK.topicCounts[t.id]||0}))];root.innerHTML=cards.map(t=>`<button type="button" class="topic-card ${t.id==="mixed"?"mixed is-selected":""}" data-topic="${escapeHtml(t.id)}"><span class="topic-icon">${escapeHtml(t.icon)}</span><strong>${escapeHtml(t.name)}</strong><small>${escapeHtml(t.desc)}</small><em>${Number(t.count).toLocaleString("vi-VN")} câu · 5 độ khó</em></button>`).join("");qsa(".topic-card",root).forEach(btn=>btn.addEventListener("click",()=>{qsa(".topic-card",root).forEach(x=>x.classList.remove("is-selected"));btn.classList.add("is-selected");state.topic=btn.dataset.topic||"mixed";$("boardTopic").value=state.topic;loadBoard(state.topic)}))}
  function renderBoardOptions(){const select=$("boardTopic"),opts=[{id:"mixed",name:"Tổng hợp Excel"},...BANK.topics];select.innerHTML=opts.map(t=>`<option value="${escapeHtml(t.id)}">${escapeHtml(t.name)}</option>`).join("");select.value=state.topic}
  async function loadBoard(topic=$("boardTopic")?.value||"mixed"){const list=$("boardList");list.innerHTML="<li>Đang tải BXH Season 1…</li>";const client=await waitClient();if(!client?.rpc){list.innerHTML="<li>Chưa kết nối được BXH.</li>";return}try{const{data,error}=await client.rpc("arena_list_leaderboard_v1",{p_topic:topic,p_limit:100});if(error)throw error;const rows=Array.isArray(data)?data:[];if(!rows.length){list.innerHTML="<li>Chưa có thành tích Rank ở chủ đề này. Bạn có thể là người đầu tiên.</li>";return}list.innerHTML=rows.map(r=>`<li class="${r.is_me?"is-me":""}"><span class="rank">#${r.rank_no}</span><span class="name">${escapeHtml(r.player_name)}${r.is_me?" · Bạn":""}</span><span class="score">${Number(r.best_score||0).toLocaleString("vi-VN")}</span><span class="level">Lv ${r.best_level||1}</span></li>`).join("")}catch(err){console.warn("[arena] load board",err);list.innerHTML="<li>BXH đang tạm thời không tải được.</li>"}}
  function bind(){qsa(".mode-card").forEach(btn=>btn.addEventListener("click",()=>{qsa(".mode-card").forEach(x=>x.classList.remove("is-selected"));btn.classList.add("is-selected");state.mode=btn.dataset.mode==="rank"?"rank":"learn"}));$("startArena").addEventListener("click",startGame);$("backSetup").addEventListener("click",showSetup);$("stopArena").addEventListener("click",()=>endGame("Bạn đã dừng lượt chơi."));$("answerForm").addEventListener("submit",e=>{e.preventDefault();if(!state.running||state.locked||!state.current)return;const result=evaluateAnswer($("answerInput").value,state.current);if(result.ok)handleCorrect(result);else if(result.grade!=="empty")handleMiss("wrong")});$("boardTopic").addEventListener("change",e=>loadBoard(e.target.value));$("refreshBoard").addEventListener("click",()=>loadBoard());document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.running&&!state.locked)state.questionStart+=Math.min(4000,state.duration*.25)});window.addEventListener("pagehide",stopAnimation,{once:true})}
  async function boot(){if(!BANK){$("setupHint").textContent="Không tải được ngân hàng câu hỏi.";return}$("bankCount").textContent=BANK.totalQuestions.toLocaleString("vi-VN");$("topicCount").textContent=BANK.topics.length;$("setupHint").textContent=`${BANK.totalQuestions.toLocaleString("vi-VN")} câu · ${BANK.topics.length} chủ đề · không lặp gần nhau; chỉ câu sai ở Học được chủ động gọi lại.`;renderTopics();renderBoardOptions();bind();syncIdentity();loadBoard("mixed")}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();
