(()=>{
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const safeUrl=v=>{const s=String(v||'').trim();if(!s||/^(javascript|data|vbscript):/i.test(s))return '';if(/^https?:\/\/[^\s<>"']+$/i.test(s))return s;return /^\.?\/?[\wÀ-ỹ()[\] ._%-]+(?:\/[\wÀ-ỹ()[\] ._?&=%#-]+)*$/i.test(s)?s:''};
  let items=[],activeTopic='';

  async function waitClient(){for(let i=0;i<50;i++){const c=window.avpSupabase||window.supabaseClient||window._supabaseClient;if(c?.rpc)return c;await new Promise(r=>setTimeout(r,100));}return null}
  function normalize(r){return {id:String(r.id||''),topic:String(r.topic||'Khác').trim(),order:Number(r.order_no||1),title:String(r.title||`Bài ${r.order_no||1}`).trim(),fileUrl:safeUrl(r.file_url),guideUrl:safeUrl(r.guide_video_url),solutionUrl:safeUrl(r.solution_video_url),hint1:String(r.hint1||'').trim(),hint2:String(r.hint2||'').trim()}}
  function topicKey(v){return String(v||'').trim().toLocaleLowerCase('vi')}
  function topics(){const m=new Map();items.forEach(x=>{const key=topicKey(x.topic);if(!m.has(key))m.set(key,{key,name:x.topic,total:0,solutions:0,min:x.order});const t=m.get(key);t.total++;t.solutions+=x.solutionUrl?1:0;t.min=Math.min(t.min,x.order)});return [...m.values()].sort((a,b)=>a.min-b.min||a.name.localeCompare(b.name,'vi'))}
  function renderTopics(){const host=$('hwTopicList');if(!host)return;const list=topics();$('hwTopicCount').textContent=list.length;if(!list.length){host.innerHTML='<div class="hw-empty"><strong>Chưa có Homework được phát hành</strong><p>Khi Admin phát hành bài đầu tiên, chủ đề sẽ xuất hiện tại đây.</p></div>';return}host.innerHTML=list.map((t,i)=>`<button class="hw-topic-row tone-${i%5}" type="button" data-topic="${esc(t.key)}"><span class="hw-topic-index">${String(i+1).padStart(2,'0')}</span><span class="hw-topic-copy"><strong>${esc(t.name)}</strong><small>${t.total} bài tập / ${t.solutions} video giải bài</small></span><span class="hw-topic-arrow">→</span></button>`).join('')}
  function action(url,label,cls){return url?`<a class="hw-action ${cls}" href="${esc(url)}" target="_blank" rel="noopener">${esc(label)}</a>`:`<span class="hw-action ${cls} disabled" aria-disabled="true">${esc(label)}</span>`}
  function card(x,i){return `<article class="hw-card tone-${i%5}"><div class="hw-card-head"><span>BÀI ${String(x.order).padStart(2,'0')}</span><h2>${esc(x.title)}</h2></div><div class="hw-actions" aria-label="Tài nguyên bài tập">${action(x.guideUrl,'▶ Video hướng dẫn','guide')}${x.fileUrl?`<a class="hw-action file" href="${esc(x.fileUrl)}" download>↓ Tải file bài tập</a>`:'<span class="hw-action file disabled" aria-disabled="true">↓ Chưa có file</span>'}${action(x.solutionUrl,x.solutionUrl?'▶ Video giải bài':'Video giải: sắp có','solution')}</div><div class="hw-hint-row"><button type="button" data-hint="1" data-id="${esc(x.id)}">Hint 1</button><button type="button" data-hint="2" data-id="${esc(x.id)}">Hint 2</button></div></article>`}
  function renderDeck(topic){const key=topicKey(topic),list=items.filter(x=>topicKey(x.topic)===key).sort((a,b)=>a.order-b.order),name=list[0]?.topic||topic;activeTopic=name;$('hwTopicView').hidden=true;$('hwExerciseView').hidden=false;$('hwActiveTopic').textContent=name;$('hwExerciseCount').textContent=`${list.length} bài tập · ${list.filter(x=>x.solutionUrl).length} video giải`;$('hwCardsTrack').innerHTML=list.map(card).join('');history.replaceState(null,'',`homework.html?topic=${encodeURIComponent(name)}`);scrollTo({top:0,behavior:'smooth'})}
  function backTopics(){$('hwExerciseView').hidden=true;$('hwTopicView').hidden=false;activeTopic='';history.replaceState(null,'','homework.html');scrollTo({top:0,behavior:'smooth'})}
  function showHint(id,n){const item=items.find(x=>x.id===id);if(!item)return;const text=n===2?item.hint2:item.hint1;$('hwHintTitle').textContent=`${item.title} · Hint ${n}`;$('hwHintText').textContent=text||`Bài này chưa có Hint ${n}.`;$('hwHintModal').hidden=false;document.body.classList.add('hw-modal-open');$('hwHintClose').focus()}
  function closeHint(){$('hwHintModal').hidden=true;document.body.classList.remove('hw-modal-open')}
  function scrollCards(dir){const track=$('hwCardsTrack');if(!track)return;const card=track.querySelector('.hw-card');const amount=(card?.getBoundingClientRect().width||360)+16;track.scrollBy({left:dir*amount,behavior:'smooth'})}
  function bind(){$('hwTopicList')?.addEventListener('click',e=>{const b=e.target.closest('[data-topic]');if(b)renderDeck(b.dataset.topic)});$('hwBackTopics')?.addEventListener('click',backTopics);$('hwCardsTrack')?.addEventListener('click',e=>{const b=e.target.closest('[data-hint]');if(b)showHint(b.dataset.id,Number(b.dataset.hint))});$('hwPrev')?.addEventListener('click',()=>scrollCards(-1));$('hwNext')?.addEventListener('click',()=>scrollCards(1));$('hwHintClose')?.addEventListener('click',closeHint);$('hwHintModal')?.addEventListener('click',e=>{if(e.target===$('hwHintModal'))closeHint()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('hwHintModal')?.hidden)closeHint()})}
  async function load(){bind();try{const c=await waitClient();if(!c)throw new Error('Supabase chưa sẵn sàng');const {data,error}=await c.rpc('homework_public_v1');if(error)throw error;items=(Array.isArray(data)?data:[]).map(normalize);renderTopics();const q=new URLSearchParams(location.search).get('topic');if(q&&items.some(x=>topicKey(x.topic)===topicKey(q)))renderDeck(q)}catch(e){console.warn('Homework load failed',e);$('hwTopicList').innerHTML='<div class="hw-empty"><strong>Chưa tải được Homework</strong><p>Hệ thống chưa lấy được danh sách bài. Hãy thử tải lại trang.</p></div>'}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();