const pgExercises = [
{ id:"if", level:"basic", title:"IF — Phân loại kết quả", topic:"Hàm điều kiện", problem:"Ô B2 chứa điểm số. Nếu B2 từ 5 trở lên trả về \"Đạt\", ngược lại trả về \"Không đạt\".", data:[["Ô","Giá trị"],["B2","7"]], hint:"Cấu trúc: IF(điều_kiện, giá_trị_nếu_đúng, giá_trị_nếu_sai)", answer:'=IF(B2>=5,"Đạt","Không đạt")', accepted:[/^=if\(b2>=5,"đạt","khôngđạt"\)$/i] },
{ id:"countif", level:"basic", title:"COUNTIF — Đếm trạng thái", topic:"Đếm theo điều kiện", problem:"Cột C2:C10 chứa trạng thái OK/NG. Hãy đếm số ô có giá trị NG.", data:[["Vùng","Dữ liệu mẫu"],["C2:C10","OK, NG, OK, OK, NG, OK, NG, OK, OK"]], hint:"COUNTIF cần vùng đếm và một điều kiện.", answer:'=COUNTIF(C2:C10,"NG")', accepted:[/^=countif\(c2:c10,"ng"\)$/i] },
{ id:"sumif", level:"basic", title:"SUMIF — Cộng theo điều kiện", topic:"Tổng theo điều kiện", problem:"A2:A6 là Model, B2:B6 là Qty. Tính tổng Qty của Model A.", data:[["Model","Qty"],["A","10"],["B","20"],["A","15"],["C","12"],["A","8"]], hint:"SUMIF(vùng_điều_kiện, điều_kiện, vùng_cần_cộng)", answer:'=SUMIF(A2:A6,"A",B2:B6)', accepted:[/^=sumif\(a2:a6,"a",b2:b6\)$/i] },
{ id:"vlookup", level:"basic", title:"VLOOKUP — Tra cứu lương", topic:"Tra cứu", problem:"Bảng A2:C5 có Mã NV, Tên, Lương. Ô E2 chứa NV02. Hãy trả về Lương bằng VLOOKUP, dò chính xác.", data:[["Mã NV","Tên","Lương"],["NV01","An","8000000"],["NV02","Bình","9500000"],["NV03","Minh","7800000"],["NV04","Lan","8700000"]], hint:"Lương nằm ở cột thứ 3 của vùng A2:C5 và cần dò chính xác.", answer:'=VLOOKUP(E2,A2:C5,3,FALSE)', accepted:[/^=vlookup\(e2,a2:c5,3,(false|0)\)$/i] },
{ id:"xlookup", level:"advanced", title:"XLOOKUP — Tra cứu hiện đại", topic:"Tra cứu", problem:"Dùng XLOOKUP để tìm Tên nhân viên tương ứng mã ở E2. Mã nằm A2:A5, Tên nằm B2:B5.", data:[["Mã NV","Tên"],["NV01","An"],["NV02","Bình"],["NV03","Minh"],["NV04","Lan"]], hint:"XLOOKUP(giá_trị_tìm, vùng_tìm, vùng_trả_về)", answer:'=XLOOKUP(E2,A2:A5,B2:B5)', accepted:[/^=xlookup\(e2,a2:a5,b2:b5\)$/i] },
{ id:"countifs", level:"advanced", title:"COUNTIFS — Nhiều điều kiện", topic:"Đếm nhiều điều kiện", problem:"A2:A20 là Model, B2:B20 là trạng thái. Đếm số dòng vừa có Model A vừa có trạng thái NG.", data:[["Điều kiện 1","Model = A"],["Điều kiện 2","Status = NG"]], hint:"COUNTIFS nhận từng cặp vùng_điều_kiện và điều_kiện.", answer:'=COUNTIFS(A2:A20,"A",B2:B20,"NG")', accepted:[/^=countifs\(a2:a20,"a",b2:b20,"ng"\)$/i] },
{ id:"sumifs", level:"advanced", title:"SUMIFS — Tổng nhiều điều kiện", topic:"Tổng nhiều điều kiện", problem:"C2:C20 là NG Qty, A2:A20 là Model, B2:B20 là Shift. Tính tổng NG Qty khi Model A và Shift Night.", data:[["Sum range","C2:C20 (NG Qty)"],["Điều kiện","Model A + Shift Night"]], hint:"SUMIFS đặt vùng cần cộng ở đối số đầu tiên.", answer:'=SUMIFS(C2:C20,A2:A20,"A",B2:B20,"Night")', accepted:[/^=sumifs\(c2:c20,a2:a20,"a",b2:b20,"night"\)$/i] },
{ id:"textjoin", level:"advanced", title:"TEXTJOIN — Ghép dữ liệu", topic:"Xử lý text", problem:"Ghép A2:A5 bằng dấu \" - \" và bỏ qua ô trống.", data:[["A2","QC"],["A3","FPC"],["A4","(trống)"],["A5","IPQC"]], hint:"Đối số thứ hai TRUE nghĩa là bỏ qua ô trống.", answer:'=TEXTJOIN(" - ",TRUE,A2:A5)', accepted:[/^=textjoin\("-",true,a2:a5\)$/i] },
{ id:"filter", level:"advanced", title:"FILTER — Lọc dữ liệu động", topic:"Dynamic Array", problem:"Lọc toàn bộ bảng A2:C20 chỉ lấy các dòng có trạng thái ở cột C bằng NG.", data:[["Bảng","A2:C20"],["Cột trạng thái","C2:C20"]], hint:"FILTER(mảng_cần_trả_về, điều_kiện_lọc)", answer:'=FILTER(A2:C20,C2:C20="NG")', accepted:[/^=filter\(a2:c20,c2:c20="ng"\)$/i] },
{ id:"ngrate", level:"basic", title:"NG Rate — Case QC thực tế", topic:"QC thực tế", problem:"Input Qty ở B2, NG Qty ở C2. Viết công thức tại D2 để tính NG Rate và tránh lỗi khi Input bằng 0.", data:[["Lot","Input Qty","NG Qty"],["LOT001","1250","17"]], hint:"Có thể kết hợp IF với phép chia: nếu Input = 0 thì trả về 0.", answer:'=IF(B2=0,0,C2/B2)', accepted:[/^=if\(b2=0,0,c2\/b2\)$/i,/^=iferror\(c2\/b2,0\)$/i] }
];

const PG_KEY = "avp_playground_progress_v1";
let pgProgress = JSON.parse(localStorage.getItem(PG_KEY) || "{}");

function pgNormalize(value){return value.toLowerCase().replace(/\s+/g,"").replace(/;/g,",").replace(/[“”]/g,'"').replace(/\$+/g,"");}
function pgSave(){localStorage.setItem(PG_KEY,JSON.stringify(pgProgress));}
function pgXp(){return Object.values(pgProgress).filter(Boolean).length*10;}
function pgRank(xp){if(xp>=100)return "Excel Explorer"; if(xp>=70)return "Formula Builder"; if(xp>=40)return "Excel Learner"; return "Excel Starter";}
function pgUpdateHeader(){const done=Object.values(pgProgress).filter(Boolean).length,xp=done*10,level=Math.floor(xp/40)+1,within=xp%40;document.getElementById("levelNumber").textContent=level;document.getElementById("xpText").textContent=xp+" XP";document.getElementById("xpBar").style.width=(xp>=100?100:(within/40)*100)+"%";document.getElementById("completedText").textContent=done+"/"+pgExercises.length+" bài hoàn thành";document.getElementById("rankText").textContent=pgRank(xp);const t=document.getElementById("summaryTitle"),p=document.getElementById("summaryText");if(done===10){t.textContent="Bạn đã hoàn thành Excel Playground!";p.textContent="🏆 Huy hiệu Excel Explorer đã được mở. Bạn đạt 100 XP ở bộ thử thách đầu tiên."}else if(done>=5){t.textContent="Bạn đang tiến bộ rất tốt";p.textContent=`Đã hoàn thành ${done}/10 bài. Còn ${10-done} bài để mở huy hiệu Excel Explorer.`}else{t.textContent="Bắt đầu hành trình Excel";p.textContent=`Đã hoàn thành ${done}/10 bài. Mỗi bài mới chính xác sẽ cộng 10 XP.`}}
function pgTable(rows){return `<div class="pg-data"><table><thead><tr>${rows[0].map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.slice(1).map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function pgRender(filter="all"){const list=document.getElementById("exerciseList");list.innerHTML="";pgExercises.filter(e=>filter==="all"||e.level===filter).forEach((e,i)=>{const card=document.createElement("article");card.className="pg-card"+(pgProgress[e.id]?" done":"");card.dataset.level=e.level;card.innerHTML=`<div class="pg-card-head"><div class="pg-index">${String(pgExercises.indexOf(e)+1).padStart(2,"0")}</div><div><h3>${e.title}</h3><p class="pg-card-sub">${e.topic}</p></div><span class="pg-level ${e.level}">${e.level==="basic"?"CƠ BẢN":"NÂNG CAO"}</span></div><div class="pg-body"><p class="pg-problem">${e.problem}</p>${pgTable(e.data)}<label class="pg-label" for="input-${e.id}">Công thức của bạn</label><div class="pg-input-row"><input id="input-${e.id}" class="pg-formula" autocomplete="off" spellcheck="false" placeholder="=..." onkeydown="if(event.key==='Enter')pgCheck('${e.id}')"><button class="pg-check" onclick="pgCheck('${e.id}')">Kiểm tra</button></div><div class="pg-actions"><button onclick="pgHint('${e.id}')">💡 Gợi ý</button><button onclick="pgAnswer('${e.id}')">👁 Hiện đáp án</button></div><div id="hint-${e.id}" class="pg-hint">${e.hint}</div><div id="feedback-${e.id}" class="pg-feedback"></div></div>`;list.appendChild(card)})}
function pgCheck(id){const e=pgExercises.find(x=>x.id===id),input=document.getElementById("input-"+id),feedback=document.getElementById("feedback-"+id),v=pgNormalize(input.value);if(!v){feedback.className="pg-feedback show info";feedback.textContent="Hãy nhập một công thức trước khi kiểm tra.";return}const ok=e.accepted.some(rx=>rx.test(v));if(ok){const first=!pgProgress[id];pgProgress[id]=true;pgSave();if(first&&window.avpRecordLearningEvent)window.avpRecordLearningEvent("playground_complete",{id});feedback.className="pg-feedback show ok";feedback.innerHTML=`✅ Chính xác! ${first?"+10 XP":"Bài này bạn đã hoàn thành trước đó."}`;document.querySelector(`#input-${id}`).closest(".pg-card").classList.add("done");pgUpdateHeader()}else{feedback.className="pg-feedback show bad";feedback.innerHTML="❌ Chưa đúng. Kiểm tra lại vùng dữ liệu, điều kiện hoặc cấu trúc hàm. Bạn có thể mở gợi ý."}}
function pgHint(id){document.getElementById("hint-"+id).classList.toggle("show")}
function pgAnswer(id){const e=pgExercises.find(x=>x.id===id),f=document.getElementById("feedback-"+id);f.className="pg-feedback show info";f.innerHTML=`Đáp án tham khảo: <span class="pg-answer">${e.answer.replace(/</g,"&lt;").replace(/>/g,"&gt;")}</span>`}

document.addEventListener("DOMContentLoaded",()=>{pgRender();pgUpdateHeader();document.querySelectorAll(".pg-filter").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".pg-filter").forEach(b=>b.classList.remove("active"));btn.classList.add("active");pgRender(btn.dataset.filter)}));document.getElementById("resetPlayground").addEventListener("click",()=>{if(confirm("Xóa tiến độ 10 bài Excel Playground trên trình duyệt này?")){pgProgress={};pgSave();pgRender(document.querySelector(".pg-filter.active").dataset.filter);pgUpdateHeader()}})});
