(() => {
  "use strict";

  window.AVP_PRACTICE_LESSONS = [
    {
      key:"clean_blank_rows_01",
      title:"Xóa dòng trống",
      topic:"clean",
      topicLabel:"Làm sạch dữ liệu",
      difficulty:"basic",
      order:1,
      maxScore:100,
      isActive:true,
      grader:"clean_blank_rows_v1",
      fileName:"AVP_01_Xoa_Dong_Trong.xlsx",
      description:"Xóa toàn bộ dòng trống trong sheet DuLieu, giữ nguyên tiêu đề và dữ liệu.",
      gradingMode:"data",
      rules:["20đ · đúng sheet","20đ · đúng tiêu đề","30đ · hết dòng trống","30đ · giữ đủ dữ liệu"]
    },
    {
      key:"clean_duplicates_02",
      title:"Xóa dữ liệu trùng",
      topic:"clean",
      topicLabel:"Làm sạch dữ liệu",
      difficulty:"basic",
      order:2,
      maxScore:100,
      isActive:true,
      grader:"clean_duplicates_v1",
      fileName:"AVP_02_Xoa_Du_Lieu_Trung.xlsx",
      description:"Xóa các dòng bị trùng hoàn toàn và giữ đúng 8 nhân viên duy nhất.",
      gradingMode:"data",
      rules:["20đ · đúng sheet","20đ · đúng tiêu đề","30đ · không còn duplicate","30đ · đủ 8 bản ghi chuẩn"]
    },
    {
      key:"clean_trim_03",
      title:"TRIM khoảng trắng",
      topic:"clean",
      topicLabel:"Làm sạch dữ liệu",
      difficulty:"basic",
      order:3,
      maxScore:100,
      isActive:true,
      grader:"clean_trim_v1",
      fileName:"AVP_03_TRIM_Khoang_Trang.xlsx",
      description:"Làm sạch khoảng trắng thừa trong cột Họ tên và Bộ phận.",
      gradingMode:"data",
      rules:["20đ · đúng sheet","20đ · đúng tiêu đề","30đ · Họ tên sạch","30đ · Bộ phận sạch"]
    },
    {
      key:"clean_case_04",
      title:"Chuẩn hóa chữ hoa/thường",
      topic:"clean",
      topicLabel:"Làm sạch dữ liệu",
      difficulty:"basic",
      order:4,
      maxScore:100,
      isActive:true,
      grader:"clean_case_v1",
      fileName:"AVP_04_Chuan_Hoa_Chu.xlsx",
      description:"Chuẩn hóa Họ tên về Proper Case và Bộ phận về chữ in hoa.",
      gradingMode:"data",
      rules:["20đ · đúng sheet","20đ · đúng tiêu đề","30đ · Họ tên đúng","30đ · Bộ phận đúng"]
    },
    {
      key:"clean_text_number_05",
      title:"Text thành Number",
      topic:"clean",
      topicLabel:"Làm sạch dữ liệu",
      difficulty:"basic",
      order:5,
      maxScore:100,
      isActive:true,
      grader:"clean_text_number_v1",
      fileName:"AVP_05_Text_Thanh_Number.xlsx",
      description:"Chuyển cột Số lượng đang lưu dạng text thành số thật.",
      gradingMode:"data",
      rules:["20đ · đúng sheet","20đ · đúng tiêu đề","30đ · toàn bộ là Number","30đ · giá trị không đổi"]
    },
    {
      key:"clean_fill_blank_06",
      title:"Điền ô trống",
      topic:"clean",
      topicLabel:"Làm sạch dữ liệu",
      difficulty:"intermediate",
      order:6,
      maxScore:100,
      isActive:true,
      grader:"clean_fill_blank_v1",
      fileName:"AVP_06_Dien_O_Trong.xlsx",
      description:"Điền đúng Bộ phận còn thiếu dựa trên dữ liệu chuẩn trong bài.",
      gradingMode:"data",
      rules:["20đ · đúng sheet","20đ · đúng tiêu đề","30đ · hết ô trống","30đ · giá trị điền đúng"]
    },
    {
      key:"clean_special_chars_07",
      title:"Xóa ký tự đặc biệt",
      topic:"clean",
      topicLabel:"Làm sạch dữ liệu",
      difficulty:"intermediate",
      order:7,
      maxScore:100,
      isActive:true,
      grader:"clean_special_v1",
      fileName:"AVP_07_Xoa_Ky_Tu_Dac_Biet.xlsx",
      description:"Loại bỏ ký tự đặc biệt không hợp lệ khỏi Mã NV nhưng giữ đúng mã.",
      gradingMode:"data",
      rules:["20đ · đúng sheet","20đ · đúng tiêu đề","30đ · hết ký tự lỗi","30đ · mã chuẩn chính xác"]
    },
    {
      key:"clean_phone_08",
      title:"Chuẩn hóa số điện thoại",
      topic:"clean",
      topicLabel:"Làm sạch dữ liệu",
      difficulty:"intermediate",
      order:8,
      maxScore:100,
      isActive:true,
      grader:"clean_phone_v1",
      fileName:"AVP_08_Chuan_Hoa_SDT.xlsx",
      description:"Chuẩn hóa số điện thoại thành chuỗi 10 chữ số bắt đầu bằng 0.",
      gradingMode:"data",
      rules:["20đ · đúng sheet","20đ · đúng tiêu đề","30đ · đúng 10 số","30đ · giữ số 0 đầu"]
    },
    {
      key:"clean_date_09",
      title:"Chuẩn hóa ngày",
      topic:"clean",
      topicLabel:"Làm sạch dữ liệu",
      difficulty:"advanced",
      order:9,
      maxScore:100,
      isActive:true,
      grader:"clean_date_v1",
      fileName:"AVP_09_Chuan_Hoa_Ngay.xlsx",
      description:"Chuyển toàn bộ cột Ngày vào dạng ngày Excel thật, không còn text.",
      gradingMode:"data",
      rules:["20đ · đúng sheet","20đ · đúng tiêu đề","30đ · kiểu Date hợp lệ","30đ · ngày không đổi"]
    },
    {
      key:"clean_mixed_10",
      title:"Làm sạch hỗn hợp",
      topic:"clean",
      topicLabel:"Làm sạch dữ liệu",
      difficulty:"advanced",
      order:10,
      maxScore:100,
      isActive:true,
      grader:"clean_mixed_v1",
      fileName:"AVP_10_Lam_Sach_Hon_Hop.xlsx",
      description:"Một file chứa nhiều lỗi: dòng trống, duplicate, khoảng trắng, kiểu số và chữ không đồng nhất.",
      gradingMode:"data",
      rules:["20đ · cấu trúc đúng","20đ · không dòng trống","20đ · không duplicate","20đ · text sạch","20đ · kiểu dữ liệu đúng"]
    },

    {
      key:"formula_if_01",
      title:"IF xác định Đạt / Không đạt",
      topic:"formula",
      topicLabel:"Công thức",
      difficulty:"basic",
      order:1,
      maxScore:100,
      isActive:true,
      grader:"formula_if_v1",
      fileName:"AVP_CT_01_IF.xlsx",
      description:"Dùng hàm IF tại cột Kết quả. Nhập tay đúng kết quả vẫn không đạt phần công thức.",
      gradingMode:"exact_formula",
      requiredFunctions:["IF"],
      rules:["20đ · đúng sheet/header","40đ · có công thức thật","20đ · dùng đúng IF","20đ · kết quả đúng"]
    },
    {
      key:"formula_revenue_02",
      title:"Tính doanh thu",
      topic:"formula",
      topicLabel:"Công thức",
      difficulty:"basic",
      order:2,
      maxScore:100,
      isActive:true,
      grader:"formula_revenue_v1",
      fileName:"AVP_CT_02_Doanh_Thu.xlsx",
      description:"Tính Doanh thu = Số lượng × Đơn giá. Cho phép công thức tương đương nhưng không được nhập tay kết quả.",
      gradingMode:"formula_result",
      rules:["20đ · đúng sheet/header","40đ · có công thức ở toàn bộ dòng","40đ · kết quả đúng"]
    }
,
    {
      key:"formula_sumif_03",
      title:"SUMIF theo bộ phận",
      topic:"formula",
      topicLabel:"Công thức",
      difficulty:"intermediate",
      order:3,
      maxScore:100,
      isActive:true,
      grader:"formula_sumif_v1",
      fileName:"AVP_CT_03_SUMIF.xlsx",
      description:"Dùng SUMIF tính tổng Số lượng của từng Bộ phận. Nhập tay đúng số vẫn mất điểm công thức.",
      gradingMode:"exact_formula",
      requiredFunctions:["SUMIF"],
      rules:["20đ · đúng cấu trúc","40đ · có công thức thật","20đ · đúng SUMIF","20đ · kết quả đúng"]
    },
    {
      key:"formula_xlookup_04",
      title:"XLOOKUP tra đơn giá",
      topic:"formula",
      topicLabel:"Công thức",
      difficulty:"advanced",
      order:4,
      maxScore:100,
      isActive:true,
      grader:"formula_xlookup_v1",
      fileName:"AVP_CT_04_XLOOKUP.xlsx",
      description:"Dùng XLOOKUP tra Đơn giá từ bảng danh mục. Bắt buộc có công thức XLOOKUP tại toàn bộ dòng.",
      gradingMode:"exact_formula",
      requiredFunctions:["XLOOKUP"],
      rules:["20đ · đúng cấu trúc","40đ · có công thức thật","20đ · đúng XLOOKUP","20đ · kết quả đúng"]
    }
,
    {
      key:"format_number_01",
      title:"Định dạng số hàng nghìn",
      topic:"format",
      topicLabel:"Định dạng",
      difficulty:"basic",
      order:1,
      maxScore:100,
      isActive:true,
      grader:"format_number_v1",
      fileName:"AVP_DD_01_Dinh_Dang_So.xlsx",
      description:"Giữ nguyên giá trị Doanh thu và định dạng B2:B6 theo kiểu số có dấu phân cách hàng nghìn.",
      gradingMode:"format",
      rules:["20đ · đúng cấu trúc","40đ · giá trị không đổi","40đ · đúng định dạng số"]
    }
  ];
})();
