(()=>{'use strict';
const FOLLOW='https://www.tiktok.com/@anhvanphongmaster',PASS='anhvanphongmaster',DAY=86400000;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().trim();
let tools=[],ideas=[],activeTool=null,timer=null,downloading=false;
function votedSet(){try{return new Set(JSON.parse(localStorage.getItem('avp_tool_idea_voted_v1')||'[]'))}catch(_){return new Set()}}
function markVoted(id){const s=votedSet();s.add(String(id));localStorage.setItem('avp_tool_idea_voted_v1',JSON.stringify([...s].slice(-200)))}
function browserKey(){let key=localStorage.getItem('avp_tool_idea_browser_v1');if(!key){key='tool-'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2));localStorage.setItem('avp_tool_idea_browser_v1',key)}return key}
async function client(){for(let i=0;i<40;i++){const sb=window.avpSupabase||window.supabaseClient;if(sb?.rpc)return sb;await new Promise(r=>setTimeout(r,100))}throw new Error('connection_unavailable')}
async function rpc(name,args={}){const sb=await client(),res=await sb.rpc(name,args);if(res.error)throw res.error;return res.data}
async function currentSession(){const sb=await client();try{const {data}=await sb.auth.getSession();return data?.session||null}catch(_){return null}}
function goLogin(){const next=(location.pathname.split('/').pop()||'tools-library.html')+location.search+location.hash;if(window.AVPAccess?.goLogin){window.AVPAccess.goLogin(next);return}location.href='auth.html?next='+encodeURIComponent(next)}
async function requireDownloadLogin(){if(window.AVPAccess?.getUser){const user=await window.AVPAccess.getUser(true);if(user)return true;goLogin();return false}const session=await currentSession();if(session?.user)return true;goLogin();return false}
function size(n){n=Number(n)||0;if(!n)return '';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n>=10||i===0?Math.round(n):n.toFixed(1)} ${u[i]}`}
function dateText(v){const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:'Chưa cập nhật'}
function dayNumber(v){const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?Date.UTC(+m[1],+m[2]-1,+m[3]):0}
function isoDay(ms){const d=new Date(ms);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`}
function todayVN(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${o.year}-${o.month}-${o.day}`}
function releaseValue(t){return t.release_date||String(t.created_at||'').slice(0,10)}
function safeTikTok(v){try{const u=new URL(String(v||''));return u.protocol==='https:'&&(u.hostname==='tiktok.com'||u.hostname.endsWith('.tiktok.com'))?u.href:''}catch(_){return ''}}
function nextRelease(){const dates=[...new Set(tools.map(releaseValue).filter(Boolean))].map(dayNumber).filter(Boolean).sort((a,b)=>a-b);if(!dates.length)return null;let anchor=dates[0];for(const d of dates.slice(1)){if(d>=anchor+7*DAY)anchor=d}return anchor+7*DAY}
function renderSchedule(){const next=nextRelease(),time=$('tlNextRelease'),note=$('tlNextReleaseNote');if(!time||!note)return;if(!next){time.textContent='Chưa xác định';note.textContent='Lịch bắt đầu khi Tool đầu tiên được phát hành.';return}const iso=isoDay(next),today=dayNumber(todayVN());time.textContent=dateText(iso);time.dateTime=iso;note.textContent=next<today?'Đã đến mốc phát hành · Tool mới sẽ mở chu kỳ 7 ngày tiếp theo.':'Tool bonus trong cùng chu kỳ không làm dời mốc này.'}
function sortedTools(rows){const mode=$('tlSort')?.value||'newest';return [...rows].sort((a,b)=>{const da=dayNumber(releaseValue(a)),db=dayNumber(releaseValue(b));if(da!==db)return mode==='oldest'?da-db:db-da;return (Number(a.sort_order)||0)-(Number(b.sort_order)||0)})}
function renderTools(){const q=norm($('tlSearch').value),filtered=tools.filter(t=>norm(`${t.title} ${t.application} ${t.description}`).includes(q)),rows=sortedTools(filtered);$('tlTotal').textContent=tools.length;$('tlCount').textContent=`${rows.length}/${tools.length} Tool`;renderSchedule();$('tlList').innerHTML=rows.length?rows.map((t,i)=>{const guide=safeTikTok(t.tiktok_url);return `<article class="tl-card"><div class="tl-order">${String(i+1).padStart(2,'0')}</div><div class="tl-card-copy"><div class="tl-card-head"><h2>${esc(t.title)}</h2><time datetime="${esc(releaseValue(t))}">🗓 ${esc(dateText(releaseValue(t)))}</time></div><span class="tl-app">Ứng dụng · ${esc(t.application||'Công việc văn phòng')}</span><p>${esc(t.description||'')}</p><small class="tl-file">📦 ZIP${t.file_size?` · ${size(t.file_size)}`:''}${Number(t.download_count)>0?` · ${Number(t.download_count)} lượt tải`:''}</small></div><div class="tl-card-actions">${guide?`<a class="tl-guide" href="${esc(guide)}" target="_blank" rel="noopener noreferrer">▶ TikTok hướng dẫn</a>`:''}<button class="tl-download" type="button" data-tool-download="${esc(t.id)}">Tải Tool ↓</button></div></article>`}).join(''):'<div class="tl-empty">Không tìm thấy Tool phù hợp.</div>'}
function statusLabel(s){return s==='planned'?'Đã lên kế hoạch':s==='building'?'Đang làm':s==='released'?'Đã phát hành':''}
function renderIdeas(){if(!ideas.length){$('tlIdeaList').innerHTML='<div class="tl-empty">Chưa có ý tưởng nào. Bạn có thể là người đầu tiên gửi đề xuất.</div>';return}const voted=votedSet();$('tlIdeaList').innerHTML=ideas.slice(0,12).map((x,i)=>{const done=voted.has(String(x.id));return `<article class="tl-idea"><div><strong>${i+1}. ${esc(x.title)}${statusLabel(x.status)?` <span class="tl-status">${statusLabel(x.status)}</span>`:''}</strong><small>${Number(x.votes)||0} người cùng cần</small></div><button class="tl-support" type="button" data-idea-support="${esc(x.id)}" ${done||x.status==='released'?'disabled':''}>${x.status==='released'?'✓ Đã phát hành':done?'✓ Đã +1':'+1 Tôi cũng cần'}</button></article>`}).join('')}
async function load(){try{const [a,b]=await Promise.all([rpc('tool_catalog_v2',{p_search:''}),rpc('tool_idea_board_v1',{p_search:'',p_limit:30})]);tools=Array.isArray(a)?a:[];ideas=Array.isArray(b)?b:[];renderTools();renderIdeas()}catch(e){console.error(e);$('tlList').innerHTML='<div class="tl-empty">Kho Tool đang cập nhật. Hãy thử lại sau.</div>';renderIdeas()}}
async function beginDownload(tool){if(!(await requireDownloadLogin()))return;openModal(tool)}
function openModal(tool){activeTool=tool;clearInterval(timer);$('tlModalTitle').textContent=tool.title;$('tlModalBody').innerHTML=`<div class="tl-question">Bạn đã follow kênh <b>Anh Văn Phòng</b> trên TikTok chưa?</div><div class="tl-actions"><button class="tl-yes" type="button" id="tlFollowYes">✓ Có rồi</button><button class="tl-no" type="button" id="tlFollowNo">Chưa follow</button></div><div class="tl-follow-hint">Follow giúp mình có thêm động lực cập nhật Tool mới. Nếu chưa follow, mình sẽ mở đúng kênh TikTok; quay lại hộp thoại này sau khi follow.</div>`;$('tlDownloadModal').hidden=false;document.body.style.overflow='hidden';$('tlFollowYes').onclick=thankYou;$('tlFollowNo').onclick=()=>{window.open(FOLLOW,'_blank','noopener,noreferrer');$('tlFollowNo').textContent='Đã mở TikTok ↗';$('tlFollowNo').disabled=true}}
function thankYou(){let left=4;$('tlModalBody').innerHTML=`<div class="tl-thanks"><div class="tl-check">✓</div><h3>Cảm ơn bạn đã ủng hộ!</h3><p>Mật khẩu giải nén của tất cả Tool:</p><div class="tl-passbox"><small>PASS GIẢI NÉN</small><div class="tl-passrow"><code>${PASS}</code><button type="button" class="tl-copy" id="tlCopyPass">Copy</button></div></div><p class="tl-countdown">Tool sẽ tự tải sau <strong id="tlSeconds">${left}</strong> giây.</p><button type="button" class="tl-skip" id="tlSkip">Bỏ qua đếm ngược & tải ngay</button></div>`;$('tlCopyPass').onclick=async()=>{try{await navigator.clipboard.writeText(PASS);$('tlCopyPass').textContent='Đã copy'}catch(_){}};$('tlSkip').onclick=downloadNow;timer=setInterval(()=>{left--;const el=$('tlSeconds');if(el)el.textContent=Math.max(left,0);if(left<=0)downloadNow()},1000)}
async function downloadNow(){clearInterval(timer);if(!activeTool||downloading)return;downloading=true;const tool=activeTool;try{const sb=await client(),{data}=await sb.auth.getSession(),session=data?.session;if(!session?.access_token){closeModal();goLogin();return}const cfg=window.AVP_SUPABASE_CONFIG||{};if(!cfg.url||!cfg.publishableKey)throw new Error('download_config_missing');$('tlModalBody').innerHTML='<div class="tl-empty">Đang chuẩn bị file tải an toàn…</div>';const res=await fetch(`${cfg.url}/functions/v1/tool-download`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,apikey:cfg.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({tool_id:tool.id})});if(res.status===401){closeModal();goLogin();return}if(!res.ok)throw new Error('download_unavailable');const blob=await res.blob(),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=String(tool.title||'tool')+'.zip';a.rel='noopener';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),30000);closeModal()}catch(e){console.error(e);$('tlModalBody').innerHTML='<div class="tl-empty">Chưa tải được Tool. Hãy đăng nhập lại hoặc thử lại sau.</div>'}finally{downloading=false}}
function closeModal(){clearInterval(timer);$('tlDownloadModal').hidden=true;document.body.style.overflow='';activeTool=null;downloading=false}
async function submitIdea(e){e.preventDefault();const input=$('tlIdeaInput'),title=input.value.trim();if(title.length<5||title.length>140){$('tlIdeaNote').textContent='Ý tưởng cần từ 5–140 ký tự.';return;}$('tlIdeaNote').textContent='Đang gửi…';try{const out=await rpc('tool_idea_suggest_v1',{p_title:title,p_browser_id:browserKey()});if(out?.topic_id)markVoted(out.topic_id);input.value='';$('tlIdeaNote').textContent=out?.released?'Ý tưởng này đã có Tool được phát hành.':'Đã nhận ý tưởng. Nếu nhiều người cùng cần, ý tưởng này sẽ tự lên đầu.';ideas=await rpc('tool_idea_board_v1',{p_search:'',p_limit:30});renderIdeas()}catch(err){$('tlIdeaNote').textContent=String(err?.message||'').includes('idea_daily_limit')?'Bạn đã gửi khá nhiều ý tưởng hôm nay. Hãy quay lại vào ngày mai.':'Chưa gửi được ý tưởng. Hãy thử lại.'}}
async function support(id,btn){btn.disabled=true;try{const out=await rpc('tool_idea_vote_v1',{p_topic_id:id,p_browser_id:browserKey()});if(out?.voted||out?.ok)markVoted(id);ideas=await rpc('tool_idea_board_v1',{p_search:'',p_limit:30});renderIdeas()}catch(_){btn.disabled=false}}
document.addEventListener('click',e=>{const d=e.target.closest('[data-tool-download]');if(d){const t=tools.find(x=>x.id===d.dataset.toolDownload);if(t)beginDownload(t);return}const s=e.target.closest('[data-idea-support]');if(s){support(s.dataset.ideaSupport,s);return}if(e.target.closest('[data-close-tool-modal]'))closeModal()});
$('tlSearch')?.addEventListener('input',renderTools);$('tlSort')?.addEventListener('change',renderTools);$('tlIdeaForm')?.addEventListener('submit',submitIdea);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('tlDownloadModal').hidden)closeModal()});load();
})();