(()=>{'use strict';
const FOLLOW='https://www.tiktok.com/@anhvanphongmaster',PASS='anhvanphongmaster';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().trim();
let tools=[],ideas=[],activeTool=null,timer=null;
function votedSet(){try{return new Set(JSON.parse(localStorage.getItem('avp_tool_idea_voted_v1')||'[]'))}catch(_){return new Set()}}
function markVoted(id){const s=votedSet();s.add(String(id));localStorage.setItem('avp_tool_idea_voted_v1',JSON.stringify([...s].slice(-200)))}
function browserKey(){let key=localStorage.getItem('avp_tool_idea_browser_v1');if(!key){key='tool-'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2));localStorage.setItem('avp_tool_idea_browser_v1',key)}return key}
async function client(){for(let i=0;i<40;i++){const sb=window.avpSupabase||window.supabaseClient;if(sb?.rpc)return sb;await new Promise(r=>setTimeout(r,100))}throw new Error('connection_unavailable')}
async function rpc(name,args={}){const sb=await client(),res=await sb.rpc(name,args);if(res.error)throw res.error;return res.data}
function size(n){n=Number(n)||0;if(!n)return '';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n>=10||i===0?Math.round(n):n.toFixed(1)} ${u[i]}`}
function renderTools(){const q=norm($('tlSearch').value);const rows=tools.filter(t=>norm(`${t.title} ${t.application} ${t.description}`).includes(q));$('tlTotal').textContent=tools.length;$('tlCount').textContent=`${rows.length}/${tools.length} Tool`;$('tlList').innerHTML=rows.length?rows.map((t,i)=>`<article class="tl-card"><div class="tl-order">${String(t.sort_order||i+1).padStart(2,'0')}</div><div><h2>${esc(t.title)}</h2><span class="tl-app">Ứng dụng · ${esc(t.application||'Công việc văn phòng')}</span><p>${esc(t.description||'')}</p><small class="tl-file">📦 ZIP${t.file_size?` · ${size(t.file_size)}`:''}${Number(t.download_count)>0?` · ${Number(t.download_count)} lượt tải`:''}</small></div><button class="tl-download" type="button" data-tool-download="${esc(t.id)}">Tải Tool ↓</button></article>`).join(''):'<div class="tl-empty">Không tìm thấy Tool phù hợp.</div>'}
function statusLabel(s){return s==='planned'?'Đã lên kế hoạch':s==='building'?'Đang làm':s==='released'?'Đã phát hành':''}
function renderIdeas(){if(!ideas.length){$('tlIdeaList').innerHTML='<div class="tl-empty">Chưa có ý tưởng nào. Bạn có thể là người đầu tiên gửi đề xuất.</div>';return}const voted=votedSet();$('tlIdeaList').innerHTML=ideas.slice(0,12).map((x,i)=>{const done=voted.has(String(x.id));return `<article class="tl-idea"><div><strong>${i+1}. ${esc(x.title)}${statusLabel(x.status)?` <span class="tl-status">${statusLabel(x.status)}</span>`:''}</strong><small>${Number(x.votes)||0} người cùng cần</small></div><button class="tl-support" type="button" data-idea-support="${esc(x.id)}" ${done||x.status==='released'?'disabled':''}>${x.status==='released'?'✓ Đã phát hành':done?'✓ Đã +1':'+1 Tôi cũng cần'}</button></article>`}).join('')}
async function load(){try{const [a,b]=await Promise.all([rpc('tool_catalog_v1',{p_search:''}),rpc('tool_idea_board_v1',{p_search:'',p_limit:30})]);tools=Array.isArray(a)?a:[];ideas=Array.isArray(b)?b:[];renderTools();renderIdeas()}catch(e){console.error(e);$('tlList').innerHTML='<div class="tl-empty">Kho Tool đang cập nhật. Hãy thử lại sau.</div>';renderIdeas()}}
function publicUrl(tool){const url=String(tool?.file_url||'').trim();return /^https:\/\//i.test(url)?url:''}
function openModal(tool){activeTool=tool;clearInterval(timer);$('tlModalTitle').textContent=tool.title;$('tlModalBody').innerHTML=`<div class="tl-question">Bạn đã follow kênh <b>Anh Văn Phòng</b> trên TikTok chưa?</div><div class="tl-actions"><button class="tl-yes" type="button" id="tlFollowYes">✓ Có rồi</button><button class="tl-no" type="button" id="tlFollowNo">Chưa follow</button></div><div class="tl-follow-hint">Follow giúp mình có thêm động lực cập nhật Tool mới. Nếu chưa follow, mình sẽ mở đúng kênh TikTok; quay lại hộp thoại này sau khi follow.</div>`;$('tlDownloadModal').hidden=false;document.body.style.overflow='hidden';$('tlFollowYes').onclick=thankYou;$('tlFollowNo').onclick=()=>{window.open(FOLLOW,'_blank','noopener,noreferrer');$('tlFollowNo').textContent='Đã mở TikTok ↗';$('tlFollowNo').disabled=true}}
function thankYou(){let left=4;$('tlModalBody').innerHTML=`<div class="tl-thanks"><div class="tl-check">✓</div><h3>Cảm ơn bạn đã ủng hộ!</h3><p>Mật khẩu giải nén của tất cả Tool:</p><div class="tl-passbox"><small>PASS GIẢI NÉN</small><div class="tl-passrow"><code>${PASS}</code><button type="button" class="tl-copy" id="tlCopyPass">Copy</button></div></div><p class="tl-countdown">Tool sẽ tự tải sau <strong id="tlSeconds">${left}</strong> giây.</p><button type="button" class="tl-skip" id="tlSkip">Bỏ qua đếm ngược & tải ngay</button></div>`;$('tlCopyPass').onclick=async()=>{try{await navigator.clipboard.writeText(PASS);$('tlCopyPass').textContent='Đã copy'}catch(_){}};$('tlSkip').onclick=downloadNow;timer=setInterval(()=>{left--;const el=$('tlSeconds');if(el)el.textContent=Math.max(left,0);if(left<=0)downloadNow()},1000)}
function downloadNow(){clearInterval(timer);if(!activeTool)return;const url=publicUrl(activeTool);if(!url){$('tlModalBody').innerHTML='<div class="tl-empty">File Tool chưa sẵn sàng. Hãy thử lại sau.</div>';return}rpc('track_download_asset',{p_source_path:activeTool.source_path}).catch(()=>{});const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.download=String(activeTool.title||'tool')+'.zip';document.body.appendChild(a);a.click();a.remove();closeModal()}
function closeModal(){clearInterval(timer);$('tlDownloadModal').hidden=true;document.body.style.overflow='';activeTool=null}
async function submitIdea(e){e.preventDefault();const input=$('tlIdeaInput'),title=input.value.trim();if(title.length<5||title.length>140){$('tlIdeaNote').textContent='Ý tưởng cần từ 5–140 ký tự.';return;}$('tlIdeaNote').textContent='Đang gửi…';try{const out=await rpc('tool_idea_suggest_v1',{p_title:title,p_browser_id:browserKey()});if(out?.topic_id)markVoted(out.topic_id);input.value='';$('tlIdeaNote').textContent=out?.released?'Ý tưởng này đã có Tool được phát hành.':'Đã nhận ý tưởng. Nếu nhiều người cùng cần, ý tưởng này sẽ tự lên đầu.';ideas=await rpc('tool_idea_board_v1',{p_search:'',p_limit:30});renderIdeas()}catch(err){$('tlIdeaNote').textContent=String(err?.message||'').includes('idea_daily_limit')?'Bạn đã gửi khá nhiều ý tưởng hôm nay. Hãy quay lại vào ngày mai.':'Chưa gửi được ý tưởng. Hãy thử lại.'}}
async function support(id,btn){btn.disabled=true;try{const out=await rpc('tool_idea_vote_v1',{p_topic_id:id,p_browser_id:browserKey()});if(out?.voted||out?.ok)markVoted(id);ideas=await rpc('tool_idea_board_v1',{p_search:'',p_limit:30});renderIdeas()}catch(_){btn.disabled=false}}
document.addEventListener('click',e=>{const d=e.target.closest('[data-tool-download]');if(d){const t=tools.find(x=>x.id===d.dataset.toolDownload);if(t)openModal(t);return}const s=e.target.closest('[data-idea-support]');if(s){support(s.dataset.ideaSupport,s);return}if(e.target.closest('[data-close-tool-modal]'))closeModal()});
$('tlSearch')?.addEventListener('input',renderTools);$('tlIdeaForm')?.addEventListener('submit',submitIdea);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('tlDownloadModal').hidden)closeModal()});load();
})();
